<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : steamclient/steammessages_cloud.steamclient.proto
 */


namespace SteamKit\Base\Unified\SteamMsgCloud;

/**
 * Protobuf service : SteamKit.Base.Unified.SteamMsgCloud.Cloud
 */
interface Cloud
{

    /**
     * @param \SteamKit\Base\Unified\SteamMsgCloud\CCloud_GetUploadServerInfo_Request
     * $input
     * @return \SteamKit\Base\Unified\SteamMsgCloud\CCloud_GetUploadServerInfo_Response
     */
    public function getUploadServerInfo(\SteamKit\Base\Unified\SteamMsgCloud\CCloud_GetUploadServerInfo_Request $input);
    /**
     * @param \SteamKit\Base\Unified\SteamMsgCloud\CCloud_BeginHTTPUpload_Request
     * $input
     * @return \SteamKit\Base\Unified\SteamMsgCloud\CCloud_BeginHTTPUpload_Response
     */
    public function beginHTTPUpload(\SteamKit\Base\Unified\SteamMsgCloud\CCloud_BeginHTTPUpload_Request $input);
    /**
     * @param \SteamKit\Base\Unified\SteamMsgCloud\CCloud_CommitHTTPUpload_Request
     * $input
     * @return \SteamKit\Base\Unified\SteamMsgCloud\CCloud_CommitHTTPUpload_Response
     */
    public function commitHTTPUpload(\SteamKit\Base\Unified\SteamMsgCloud\CCloud_CommitHTTPUpload_Request $input);
    /**
     * @param \SteamKit\Base\Unified\SteamMsgCloud\CCloud_GetFileDetails_Request $input
     * @return \SteamKit\Base\Unified\SteamMsgCloud\CCloud_GetFileDetails_Response
     */
    public function getFileDetails(\SteamKit\Base\Unified\SteamMsgCloud\CCloud_GetFileDetails_Request $input);
    /**
     * @param \SteamKit\Base\Unified\SteamMsgCloud\CCloud_EnumerateUserFiles_Request
     * $input
     * @return \SteamKit\Base\Unified\SteamMsgCloud\CCloud_EnumerateUserFiles_Response
     */
    public function enumerateUserFiles(\SteamKit\Base\Unified\SteamMsgCloud\CCloud_EnumerateUserFiles_Request $input);
    /**
     * @param \SteamKit\Base\Unified\SteamMsgCloud\CCloud_Delete_Request $input
     * @return \SteamKit\Base\Unified\SteamMsgCloud\CCloud_Delete_Response
     */
    public function delete(\SteamKit\Base\Unified\SteamMsgCloud\CCloud_Delete_Request $input);
    /**
     * @param
     * \SteamKit\Base\Unified\SteamMsgCloud\CCloud_GetClientEncryptionKey_Request
     * $input
     * @return
     * \SteamKit\Base\Unified\SteamMsgCloud\CCloud_GetClientEncryptionKey_Response
     */
    public function getClientEncryptionKey(\SteamKit\Base\Unified\SteamMsgCloud\CCloud_GetClientEncryptionKey_Request $input);
    /**
     * @param \SteamKit\Base\Unified\SteamMsgCloud\CCloud_CDNReport_Notification $input
     * @return \SteamKit\Base\Unified\SteamMsgUnifiedBase\NoResponse
     */
    public function cDNReport(\SteamKit\Base\Unified\SteamMsgCloud\CCloud_CDNReport_Notification $input);
    /**
     * @param
     * \SteamKit\Base\Unified\SteamMsgCloud\CCloud_ExternalStorageTransferReport_Notification
     * $input
     * @return \SteamKit\Base\Unified\SteamMsgUnifiedBase\NoResponse
     */
    public function externalStorageTransferReport(\SteamKit\Base\Unified\SteamMsgCloud\CCloud_ExternalStorageTransferReport_Notification $input);
    /**
     * @param \SteamKit\Base\Unified\SteamMsgCloud\CCloud_ClientBeginFileUpload_Request
     * $input
     * @return
     * \SteamKit\Base\Unified\SteamMsgCloud\CCloud_ClientBeginFileUpload_Response
     */
    public function clientBeginFileUpload(\SteamKit\Base\Unified\SteamMsgCloud\CCloud_ClientBeginFileUpload_Request $input);
    /**
     * @param
     * \SteamKit\Base\Unified\SteamMsgCloud\CCloud_ClientCommitFileUpload_Request
     * $input
     * @return
     * \SteamKit\Base\Unified\SteamMsgCloud\CCloud_ClientCommitFileUpload_Response
     */
    public function clientCommitFileUpload(\SteamKit\Base\Unified\SteamMsgCloud\CCloud_ClientCommitFileUpload_Request $input);
    /**
     * @param \SteamKit\Base\Unified\SteamMsgCloud\CCloud_ClientFileDownload_Request
     * $input
     * @return \SteamKit\Base\Unified\SteamMsgCloud\CCloud_ClientFileDownload_Response
     */
    public function clientFileDownload(\SteamKit\Base\Unified\SteamMsgCloud\CCloud_ClientFileDownload_Request $input);
    /**
     * @param \SteamKit\Base\Unified\SteamMsgCloud\CCloud_ClientDeleteFile_Request
     * $input
     * @return \SteamKit\Base\Unified\SteamMsgCloud\CCloud_ClientDeleteFile_Response
     */
    public function clientDeleteFile(\SteamKit\Base\Unified\SteamMsgCloud\CCloud_ClientDeleteFile_Request $input);

}

