<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : steamclient/steammessages_twofactor.steamclient.proto
 */


namespace SteamKit\Base\Unified\SteamMsgTwoFactor;

/**
 * Protobuf message :
 * SteamKit.Base.Unified.SteamMsgTwoFactor.CTwoFactor_RemoveAuthenticator_Response
 */
class CTwoFactor_RemoveAuthenticator_Response extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * success optional bool = 1
     *
     * @var bool
     */
    protected $success = null;

    /**
     * server_time optional uint64 = 3
     *
     * @var int
     */
    protected $server_time = null;

    /**
     * revocation_attempts_remaining optional uint32 = 5
     *
     * @var int
     */
    protected $revocation_attempts_remaining = null;

    /**
     * Check if 'success' has a value
     *
     * @return bool
     */
    public function hasSuccess()
    {
        return $this->success !== null;
    }

    /**
     * Get 'success' value
     *
     * @return bool
     */
    public function getSuccess()
    {
        return $this->success;
    }

    /**
     * Set 'success' value
     *
     * @param bool $value
     */
    public function setSuccess($value = null)
    {
        $this->success = $value;
    }

    /**
     * Check if 'server_time' has a value
     *
     * @return bool
     */
    public function hasServerTime()
    {
        return $this->server_time !== null;
    }

    /**
     * Get 'server_time' value
     *
     * @return int
     */
    public function getServerTime()
    {
        return $this->server_time;
    }

    /**
     * Set 'server_time' value
     *
     * @param int $value
     */
    public function setServerTime($value = null)
    {
        $this->server_time = $value;
    }

    /**
     * Check if 'revocation_attempts_remaining' has a value
     *
     * @return bool
     */
    public function hasRevocationAttemptsRemaining()
    {
        return $this->revocation_attempts_remaining !== null;
    }

    /**
     * Get 'revocation_attempts_remaining' value
     *
     * @return int
     */
    public function getRevocationAttemptsRemaining()
    {
        return $this->revocation_attempts_remaining;
    }

    /**
     * Set 'revocation_attempts_remaining' value
     *
     * @param int $value
     */
    public function setRevocationAttemptsRemaining($value = null)
    {
        $this->revocation_attempts_remaining = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        $message = new self();
        $values  = array_merge([
            'success' => null,
            'server_time' => null,
            'revocation_attempts_remaining' => null
        ], $values);

        $message->setSuccess($values['success']);
        $message->setServerTime($values['server_time']);
        $message->setRevocationAttemptsRemaining($values['revocation_attempts_remaining']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'CTwoFactor_RemoveAuthenticator_Response',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'success',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BOOL(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'server_time',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT64(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 5,
                    'name' => 'revocation_attempts_remaining',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->success !== null) {
            $writer->writeVarint($stream, 8);
            $writer->writeBool($stream, $this->success);
        }

        if ($this->server_time !== null) {
            $writer->writeVarint($stream, 24);
            $writer->writeVarint($stream, $this->server_time);
        }

        if ($this->revocation_attempts_remaining !== null) {
            $writer->writeVarint($stream, 40);
            $writer->writeVarint($stream, $this->revocation_attempts_remaining);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 8);

                $this->success = $reader->readBool($stream);

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 4);

                $this->server_time = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 5) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->revocation_attempts_remaining = $reader->readVarint($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->success !== null) {
            $size += 1;
            $size += 1;
        }

        if ($this->server_time !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->server_time);
        }

        if ($this->revocation_attempts_remaining !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->revocation_attempts_remaining);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->success = null;
        $this->server_time = null;
        $this->revocation_attempts_remaining = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \SteamKit\Base\Unified\SteamMsgTwoFactor\CTwoFactor_RemoveAuthenticator_Response) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->success = ($message->success !== null) ? $message->success : $this->success;
        $this->server_time = ($message->server_time !== null) ? $message->server_time : $this->server_time;
        $this->revocation_attempts_remaining = ($message->revocation_attempts_remaining !== null) ? $message->revocation_attempts_remaining : $this->revocation_attempts_remaining;
    }


}

