<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : steamclient/steammessages_clientserver_2.proto
 */


namespace SteamKit\Base\SteamMsgClientServer2;

/**
 * Protobuf message :
 * SteamKit.Base.SteamMsgClientServer2.CMsgClientDeauthorizeDeviceRequest
 */
class CMsgClientDeauthorizeDeviceRequest extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * deauthorization_account_id optional uint32 = 1
     *
     * @var int
     */
    protected $deauthorization_account_id = null;

    /**
     * deauthorization_device_token optional uint64 = 2
     *
     * @var int
     */
    protected $deauthorization_device_token = null;

    /**
     * Check if 'deauthorization_account_id' has a value
     *
     * @return bool
     */
    public function hasDeauthorizationAccountId()
    {
        return $this->deauthorization_account_id !== null;
    }

    /**
     * Get 'deauthorization_account_id' value
     *
     * @return int
     */
    public function getDeauthorizationAccountId()
    {
        return $this->deauthorization_account_id;
    }

    /**
     * Set 'deauthorization_account_id' value
     *
     * @param int $value
     */
    public function setDeauthorizationAccountId($value = null)
    {
        $this->deauthorization_account_id = $value;
    }

    /**
     * Check if 'deauthorization_device_token' has a value
     *
     * @return bool
     */
    public function hasDeauthorizationDeviceToken()
    {
        return $this->deauthorization_device_token !== null;
    }

    /**
     * Get 'deauthorization_device_token' value
     *
     * @return int
     */
    public function getDeauthorizationDeviceToken()
    {
        return $this->deauthorization_device_token;
    }

    /**
     * Set 'deauthorization_device_token' value
     *
     * @param int $value
     */
    public function setDeauthorizationDeviceToken($value = null)
    {
        $this->deauthorization_device_token = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        $message = new self();
        $values  = array_merge([
            'deauthorization_account_id' => null,
            'deauthorization_device_token' => null
        ], $values);

        $message->setDeauthorizationAccountId($values['deauthorization_account_id']);
        $message->setDeauthorizationDeviceToken($values['deauthorization_device_token']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'CMsgClientDeauthorizeDeviceRequest',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'deauthorization_account_id',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'deauthorization_device_token',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT64(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->deauthorization_account_id !== null) {
            $writer->writeVarint($stream, 8);
            $writer->writeVarint($stream, $this->deauthorization_account_id);
        }

        if ($this->deauthorization_device_token !== null) {
            $writer->writeVarint($stream, 16);
            $writer->writeVarint($stream, $this->deauthorization_device_token);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->deauthorization_account_id = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 4);

                $this->deauthorization_device_token = $reader->readVarint($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->deauthorization_account_id !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->deauthorization_account_id);
        }

        if ($this->deauthorization_device_token !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->deauthorization_device_token);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->deauthorization_account_id = null;
        $this->deauthorization_device_token = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \SteamKit\Base\SteamMsgClientServer2\CMsgClientDeauthorizeDeviceRequest) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->deauthorization_account_id = ($message->deauthorization_account_id !== null) ? $message->deauthorization_account_id : $this->deauthorization_account_id;
        $this->deauthorization_device_token = ($message->deauthorization_device_token !== null) ? $message->deauthorization_device_token : $this->deauthorization_device_token;
    }


}

