<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : steamclient/steammessages_clientserver_2.proto
 */


namespace SteamKit\Base\SteamMsgClientServer2;

/**
 * Protobuf message : SteamKit.Base.SteamMsgClientServer2.CMsgClientGMSServerQuery
 */
class CMsgClientGMSServerQuery extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * app_id optional uint32 = 1
     *
     * @var int
     */
    protected $app_id = null;

    /**
     * geo_location_ip optional uint32 = 2
     *
     * @var int
     */
    protected $geo_location_ip = null;

    /**
     * region_code optional uint32 = 3
     *
     * @var int
     */
    protected $region_code = null;

    /**
     * filter_text optional string = 4
     *
     * @var string
     */
    protected $filter_text = null;

    /**
     * max_servers optional uint32 = 5
     *
     * @var int
     */
    protected $max_servers = null;

    /**
     * Check if 'app_id' has a value
     *
     * @return bool
     */
    public function hasAppId()
    {
        return $this->app_id !== null;
    }

    /**
     * Get 'app_id' value
     *
     * @return int
     */
    public function getAppId()
    {
        return $this->app_id;
    }

    /**
     * Set 'app_id' value
     *
     * @param int $value
     */
    public function setAppId($value = null)
    {
        $this->app_id = $value;
    }

    /**
     * Check if 'geo_location_ip' has a value
     *
     * @return bool
     */
    public function hasGeoLocationIp()
    {
        return $this->geo_location_ip !== null;
    }

    /**
     * Get 'geo_location_ip' value
     *
     * @return int
     */
    public function getGeoLocationIp()
    {
        return $this->geo_location_ip;
    }

    /**
     * Set 'geo_location_ip' value
     *
     * @param int $value
     */
    public function setGeoLocationIp($value = null)
    {
        $this->geo_location_ip = $value;
    }

    /**
     * Check if 'region_code' has a value
     *
     * @return bool
     */
    public function hasRegionCode()
    {
        return $this->region_code !== null;
    }

    /**
     * Get 'region_code' value
     *
     * @return int
     */
    public function getRegionCode()
    {
        return $this->region_code;
    }

    /**
     * Set 'region_code' value
     *
     * @param int $value
     */
    public function setRegionCode($value = null)
    {
        $this->region_code = $value;
    }

    /**
     * Check if 'filter_text' has a value
     *
     * @return bool
     */
    public function hasFilterText()
    {
        return $this->filter_text !== null;
    }

    /**
     * Get 'filter_text' value
     *
     * @return string
     */
    public function getFilterText()
    {
        return $this->filter_text;
    }

    /**
     * Set 'filter_text' value
     *
     * @param string $value
     */
    public function setFilterText($value = null)
    {
        $this->filter_text = $value;
    }

    /**
     * Check if 'max_servers' has a value
     *
     * @return bool
     */
    public function hasMaxServers()
    {
        return $this->max_servers !== null;
    }

    /**
     * Get 'max_servers' value
     *
     * @return int
     */
    public function getMaxServers()
    {
        return $this->max_servers;
    }

    /**
     * Set 'max_servers' value
     *
     * @param int $value
     */
    public function setMaxServers($value = null)
    {
        $this->max_servers = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        $message = new self();
        $values  = array_merge([
            'app_id' => null,
            'geo_location_ip' => null,
            'region_code' => null,
            'filter_text' => null,
            'max_servers' => null
        ], $values);

        $message->setAppId($values['app_id']);
        $message->setGeoLocationIp($values['geo_location_ip']);
        $message->setRegionCode($values['region_code']);
        $message->setFilterText($values['filter_text']);
        $message->setMaxServers($values['max_servers']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'CMsgClientGMSServerQuery',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'app_id',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'geo_location_ip',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'region_code',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 4,
                    'name' => 'filter_text',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_STRING(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 5,
                    'name' => 'max_servers',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->app_id !== null) {
            $writer->writeVarint($stream, 8);
            $writer->writeVarint($stream, $this->app_id);
        }

        if ($this->geo_location_ip !== null) {
            $writer->writeVarint($stream, 16);
            $writer->writeVarint($stream, $this->geo_location_ip);
        }

        if ($this->region_code !== null) {
            $writer->writeVarint($stream, 24);
            $writer->writeVarint($stream, $this->region_code);
        }

        if ($this->filter_text !== null) {
            $writer->writeVarint($stream, 34);
            $writer->writeString($stream, $this->filter_text);
        }

        if ($this->max_servers !== null) {
            $writer->writeVarint($stream, 40);
            $writer->writeVarint($stream, $this->max_servers);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->app_id = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->geo_location_ip = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->region_code = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 4) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                $this->filter_text = $reader->readString($stream);

                continue;
            }

            if ($tag === 5) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->max_servers = $reader->readVarint($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->app_id !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->app_id);
        }

        if ($this->geo_location_ip !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->geo_location_ip);
        }

        if ($this->region_code !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->region_code);
        }

        if ($this->filter_text !== null) {
            $size += 1;
            $size += $calculator->computeStringSize($this->filter_text);
        }

        if ($this->max_servers !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->max_servers);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->app_id = null;
        $this->geo_location_ip = null;
        $this->region_code = null;
        $this->filter_text = null;
        $this->max_servers = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \SteamKit\Base\SteamMsgClientServer2\CMsgClientGMSServerQuery) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->app_id = ($message->app_id !== null) ? $message->app_id : $this->app_id;
        $this->geo_location_ip = ($message->geo_location_ip !== null) ? $message->geo_location_ip : $this->geo_location_ip;
        $this->region_code = ($message->region_code !== null) ? $message->region_code : $this->region_code;
        $this->filter_text = ($message->filter_text !== null) ? $message->filter_text : $this->filter_text;
        $this->max_servers = ($message->max_servers !== null) ? $message->max_servers : $this->max_servers;
    }


}

