<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : steamclient/steammessages_clientserver.proto
 */


namespace SteamKit\Base\SteamMsgClientServer;

/**
 * Protobuf message : SteamKit.Base.SteamMsgClientServer.CMsgClientMMSSetLobbyData
 */
class CMsgClientMMSSetLobbyData extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * app_id optional uint32 = 1
     *
     * @var int
     */
    protected $app_id = null;

    /**
     * steam_id_lobby optional fixed64 = 2
     *
     * @var int
     */
    protected $steam_id_lobby = null;

    /**
     * steam_id_member optional fixed64 = 3
     *
     * @var int
     */
    protected $steam_id_member = null;

    /**
     * max_members optional int32 = 4
     *
     * @var int
     */
    protected $max_members = null;

    /**
     * lobby_type optional int32 = 5
     *
     * @var int
     */
    protected $lobby_type = null;

    /**
     * lobby_flags optional int32 = 6
     *
     * @var int
     */
    protected $lobby_flags = null;

    /**
     * metadata optional bytes = 7
     *
     * @var \Protobuf\Stream
     */
    protected $metadata = null;

    /**
     * Check if 'app_id' has a value
     *
     * @return bool
     */
    public function hasAppId()
    {
        return $this->app_id !== null;
    }

    /**
     * Get 'app_id' value
     *
     * @return int
     */
    public function getAppId()
    {
        return $this->app_id;
    }

    /**
     * Set 'app_id' value
     *
     * @param int $value
     */
    public function setAppId($value = null)
    {
        $this->app_id = $value;
    }

    /**
     * Check if 'steam_id_lobby' has a value
     *
     * @return bool
     */
    public function hasSteamIdLobby()
    {
        return $this->steam_id_lobby !== null;
    }

    /**
     * Get 'steam_id_lobby' value
     *
     * @return int
     */
    public function getSteamIdLobby()
    {
        return $this->steam_id_lobby;
    }

    /**
     * Set 'steam_id_lobby' value
     *
     * @param int $value
     */
    public function setSteamIdLobby($value = null)
    {
        $this->steam_id_lobby = $value;
    }

    /**
     * Check if 'steam_id_member' has a value
     *
     * @return bool
     */
    public function hasSteamIdMember()
    {
        return $this->steam_id_member !== null;
    }

    /**
     * Get 'steam_id_member' value
     *
     * @return int
     */
    public function getSteamIdMember()
    {
        return $this->steam_id_member;
    }

    /**
     * Set 'steam_id_member' value
     *
     * @param int $value
     */
    public function setSteamIdMember($value = null)
    {
        $this->steam_id_member = $value;
    }

    /**
     * Check if 'max_members' has a value
     *
     * @return bool
     */
    public function hasMaxMembers()
    {
        return $this->max_members !== null;
    }

    /**
     * Get 'max_members' value
     *
     * @return int
     */
    public function getMaxMembers()
    {
        return $this->max_members;
    }

    /**
     * Set 'max_members' value
     *
     * @param int $value
     */
    public function setMaxMembers($value = null)
    {
        $this->max_members = $value;
    }

    /**
     * Check if 'lobby_type' has a value
     *
     * @return bool
     */
    public function hasLobbyType()
    {
        return $this->lobby_type !== null;
    }

    /**
     * Get 'lobby_type' value
     *
     * @return int
     */
    public function getLobbyType()
    {
        return $this->lobby_type;
    }

    /**
     * Set 'lobby_type' value
     *
     * @param int $value
     */
    public function setLobbyType($value = null)
    {
        $this->lobby_type = $value;
    }

    /**
     * Check if 'lobby_flags' has a value
     *
     * @return bool
     */
    public function hasLobbyFlags()
    {
        return $this->lobby_flags !== null;
    }

    /**
     * Get 'lobby_flags' value
     *
     * @return int
     */
    public function getLobbyFlags()
    {
        return $this->lobby_flags;
    }

    /**
     * Set 'lobby_flags' value
     *
     * @param int $value
     */
    public function setLobbyFlags($value = null)
    {
        $this->lobby_flags = $value;
    }

    /**
     * Check if 'metadata' has a value
     *
     * @return bool
     */
    public function hasMetadata()
    {
        return $this->metadata !== null;
    }

    /**
     * Get 'metadata' value
     *
     * @return \Protobuf\Stream
     */
    public function getMetadata()
    {
        return $this->metadata;
    }

    /**
     * Set 'metadata' value
     *
     * @param \Protobuf\Stream $value
     */
    public function setMetadata($value = null)
    {
        if ($value !== null && ! $value instanceof \Protobuf\Stream) {
            $value = \Protobuf\Stream::wrap($value);
        }

        $this->metadata = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        $message = new self();
        $values  = array_merge([
            'app_id' => null,
            'steam_id_lobby' => null,
            'steam_id_member' => null,
            'max_members' => null,
            'lobby_type' => null,
            'lobby_flags' => null,
            'metadata' => null
        ], $values);

        $message->setAppId($values['app_id']);
        $message->setSteamIdLobby($values['steam_id_lobby']);
        $message->setSteamIdMember($values['steam_id_member']);
        $message->setMaxMembers($values['max_members']);
        $message->setLobbyType($values['lobby_type']);
        $message->setLobbyFlags($values['lobby_flags']);
        $message->setMetadata($values['metadata']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'CMsgClientMMSSetLobbyData',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'app_id',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'steam_id_lobby',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_FIXED64(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'steam_id_member',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_FIXED64(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 4,
                    'name' => 'max_members',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_INT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 5,
                    'name' => 'lobby_type',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_INT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 6,
                    'name' => 'lobby_flags',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_INT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 7,
                    'name' => 'metadata',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BYTES(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->app_id !== null) {
            $writer->writeVarint($stream, 8);
            $writer->writeVarint($stream, $this->app_id);
        }

        if ($this->steam_id_lobby !== null) {
            $writer->writeVarint($stream, 17);
            $writer->writeFixed64($stream, $this->steam_id_lobby);
        }

        if ($this->steam_id_member !== null) {
            $writer->writeVarint($stream, 25);
            $writer->writeFixed64($stream, $this->steam_id_member);
        }

        if ($this->max_members !== null) {
            $writer->writeVarint($stream, 32);
            $writer->writeVarint($stream, $this->max_members);
        }

        if ($this->lobby_type !== null) {
            $writer->writeVarint($stream, 40);
            $writer->writeVarint($stream, $this->lobby_type);
        }

        if ($this->lobby_flags !== null) {
            $writer->writeVarint($stream, 48);
            $writer->writeVarint($stream, $this->lobby_flags);
        }

        if ($this->metadata !== null) {
            $writer->writeVarint($stream, 58);
            $writer->writeByteStream($stream, $this->metadata);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->app_id = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 6);

                $this->steam_id_lobby = $reader->readFixed64($stream);

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 6);

                $this->steam_id_member = $reader->readFixed64($stream);

                continue;
            }

            if ($tag === 4) {
                \Protobuf\WireFormat::assertWireType($wire, 5);

                $this->max_members = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 5) {
                \Protobuf\WireFormat::assertWireType($wire, 5);

                $this->lobby_type = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 6) {
                \Protobuf\WireFormat::assertWireType($wire, 5);

                $this->lobby_flags = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 7) {
                \Protobuf\WireFormat::assertWireType($wire, 12);

                $this->metadata = $reader->readByteStream($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->app_id !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->app_id);
        }

        if ($this->steam_id_lobby !== null) {
            $size += 1;
            $size += 8;
        }

        if ($this->steam_id_member !== null) {
            $size += 1;
            $size += 8;
        }

        if ($this->max_members !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->max_members);
        }

        if ($this->lobby_type !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->lobby_type);
        }

        if ($this->lobby_flags !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->lobby_flags);
        }

        if ($this->metadata !== null) {
            $size += 1;
            $size += $calculator->computeByteStreamSize($this->metadata);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->app_id = null;
        $this->steam_id_lobby = null;
        $this->steam_id_member = null;
        $this->max_members = null;
        $this->lobby_type = null;
        $this->lobby_flags = null;
        $this->metadata = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \SteamKit\Base\SteamMsgClientServer\CMsgClientMMSSetLobbyData) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->app_id = ($message->app_id !== null) ? $message->app_id : $this->app_id;
        $this->steam_id_lobby = ($message->steam_id_lobby !== null) ? $message->steam_id_lobby : $this->steam_id_lobby;
        $this->steam_id_member = ($message->steam_id_member !== null) ? $message->steam_id_member : $this->steam_id_member;
        $this->max_members = ($message->max_members !== null) ? $message->max_members : $this->max_members;
        $this->lobby_type = ($message->lobby_type !== null) ? $message->lobby_type : $this->lobby_type;
        $this->lobby_flags = ($message->lobby_flags !== null) ? $message->lobby_flags : $this->lobby_flags;
        $this->metadata = ($message->metadata !== null) ? $message->metadata : $this->metadata;
    }


}

