<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : steamclient/steammessages_clientserver.proto
 */


namespace SteamKit\Base\SteamMsgClientServer;

/**
 * Protobuf message : SteamKit.Base.SteamMsgClientServer.CMsgClientChangeStatus
 */
class CMsgClientChangeStatus extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * persona_state optional uint32 = 1
     *
     * @var int
     */
    protected $persona_state = null;

    /**
     * player_name optional string = 2
     *
     * @var string
     */
    protected $player_name = null;

    /**
     * is_auto_generated_name optional bool = 3
     *
     * @var bool
     */
    protected $is_auto_generated_name = null;

    /**
     * high_priority optional bool = 4
     *
     * @var bool
     */
    protected $high_priority = null;

    /**
     * persona_set_by_user optional bool = 5
     *
     * @var bool
     */
    protected $persona_set_by_user = null;

    /**
     * persona_state_flags optional uint32 = 6
     *
     * @var int
     */
    protected $persona_state_flags = null;

    /**
     * {@inheritdoc}
     */
    public function __construct($stream = null, \Protobuf\Configuration $configuration = null)
    {
        $this->persona_state_flags = '0';

        parent::__construct($stream, $configuration);
    }

    /**
     * Check if 'persona_state' has a value
     *
     * @return bool
     */
    public function hasPersonaState()
    {
        return $this->persona_state !== null;
    }

    /**
     * Get 'persona_state' value
     *
     * @return int
     */
    public function getPersonaState()
    {
        return $this->persona_state;
    }

    /**
     * Set 'persona_state' value
     *
     * @param int $value
     */
    public function setPersonaState($value = null)
    {
        $this->persona_state = $value;
    }

    /**
     * Check if 'player_name' has a value
     *
     * @return bool
     */
    public function hasPlayerName()
    {
        return $this->player_name !== null;
    }

    /**
     * Get 'player_name' value
     *
     * @return string
     */
    public function getPlayerName()
    {
        return $this->player_name;
    }

    /**
     * Set 'player_name' value
     *
     * @param string $value
     */
    public function setPlayerName($value = null)
    {
        $this->player_name = $value;
    }

    /**
     * Check if 'is_auto_generated_name' has a value
     *
     * @return bool
     */
    public function hasIsAutoGeneratedName()
    {
        return $this->is_auto_generated_name !== null;
    }

    /**
     * Get 'is_auto_generated_name' value
     *
     * @return bool
     */
    public function getIsAutoGeneratedName()
    {
        return $this->is_auto_generated_name;
    }

    /**
     * Set 'is_auto_generated_name' value
     *
     * @param bool $value
     */
    public function setIsAutoGeneratedName($value = null)
    {
        $this->is_auto_generated_name = $value;
    }

    /**
     * Check if 'high_priority' has a value
     *
     * @return bool
     */
    public function hasHighPriority()
    {
        return $this->high_priority !== null;
    }

    /**
     * Get 'high_priority' value
     *
     * @return bool
     */
    public function getHighPriority()
    {
        return $this->high_priority;
    }

    /**
     * Set 'high_priority' value
     *
     * @param bool $value
     */
    public function setHighPriority($value = null)
    {
        $this->high_priority = $value;
    }

    /**
     * Check if 'persona_set_by_user' has a value
     *
     * @return bool
     */
    public function hasPersonaSetByUser()
    {
        return $this->persona_set_by_user !== null;
    }

    /**
     * Get 'persona_set_by_user' value
     *
     * @return bool
     */
    public function getPersonaSetByUser()
    {
        return $this->persona_set_by_user;
    }

    /**
     * Set 'persona_set_by_user' value
     *
     * @param bool $value
     */
    public function setPersonaSetByUser($value = null)
    {
        $this->persona_set_by_user = $value;
    }

    /**
     * Check if 'persona_state_flags' has a value
     *
     * @return bool
     */
    public function hasPersonaStateFlags()
    {
        return $this->persona_state_flags !== null;
    }

    /**
     * Get 'persona_state_flags' value
     *
     * @return int
     */
    public function getPersonaStateFlags()
    {
        return $this->persona_state_flags;
    }

    /**
     * Set 'persona_state_flags' value
     *
     * @param int $value
     */
    public function setPersonaStateFlags($value = null)
    {
        $this->persona_state_flags = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        $message = new self();
        $values  = array_merge([
            'persona_state' => null,
            'player_name' => null,
            'is_auto_generated_name' => null,
            'high_priority' => null,
            'persona_set_by_user' => null,
            'persona_state_flags' => '0'
        ], $values);

        $message->setPersonaState($values['persona_state']);
        $message->setPlayerName($values['player_name']);
        $message->setIsAutoGeneratedName($values['is_auto_generated_name']);
        $message->setHighPriority($values['high_priority']);
        $message->setPersonaSetByUser($values['persona_set_by_user']);
        $message->setPersonaStateFlags($values['persona_state_flags']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'CMsgClientChangeStatus',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'persona_state',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'player_name',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_STRING(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'is_auto_generated_name',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BOOL(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 4,
                    'name' => 'high_priority',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BOOL(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 5,
                    'name' => 'persona_set_by_user',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BOOL(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 6,
                    'name' => 'persona_state_flags',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL(),
                    'default_value' => '0'
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->persona_state !== null) {
            $writer->writeVarint($stream, 8);
            $writer->writeVarint($stream, $this->persona_state);
        }

        if ($this->player_name !== null) {
            $writer->writeVarint($stream, 18);
            $writer->writeString($stream, $this->player_name);
        }

        if ($this->is_auto_generated_name !== null) {
            $writer->writeVarint($stream, 24);
            $writer->writeBool($stream, $this->is_auto_generated_name);
        }

        if ($this->high_priority !== null) {
            $writer->writeVarint($stream, 32);
            $writer->writeBool($stream, $this->high_priority);
        }

        if ($this->persona_set_by_user !== null) {
            $writer->writeVarint($stream, 40);
            $writer->writeBool($stream, $this->persona_set_by_user);
        }

        if ($this->persona_state_flags !== null) {
            $writer->writeVarint($stream, 48);
            $writer->writeVarint($stream, $this->persona_state_flags);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->persona_state = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                $this->player_name = $reader->readString($stream);

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 8);

                $this->is_auto_generated_name = $reader->readBool($stream);

                continue;
            }

            if ($tag === 4) {
                \Protobuf\WireFormat::assertWireType($wire, 8);

                $this->high_priority = $reader->readBool($stream);

                continue;
            }

            if ($tag === 5) {
                \Protobuf\WireFormat::assertWireType($wire, 8);

                $this->persona_set_by_user = $reader->readBool($stream);

                continue;
            }

            if ($tag === 6) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->persona_state_flags = $reader->readVarint($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->persona_state !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->persona_state);
        }

        if ($this->player_name !== null) {
            $size += 1;
            $size += $calculator->computeStringSize($this->player_name);
        }

        if ($this->is_auto_generated_name !== null) {
            $size += 1;
            $size += 1;
        }

        if ($this->high_priority !== null) {
            $size += 1;
            $size += 1;
        }

        if ($this->persona_set_by_user !== null) {
            $size += 1;
            $size += 1;
        }

        if ($this->persona_state_flags !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->persona_state_flags);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->persona_state = null;
        $this->player_name = null;
        $this->is_auto_generated_name = null;
        $this->high_priority = null;
        $this->persona_set_by_user = null;
        $this->persona_state_flags = '0';
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \SteamKit\Base\SteamMsgClientServer\CMsgClientChangeStatus) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->persona_state = ($message->persona_state !== null) ? $message->persona_state : $this->persona_state;
        $this->player_name = ($message->player_name !== null) ? $message->player_name : $this->player_name;
        $this->is_auto_generated_name = ($message->is_auto_generated_name !== null) ? $message->is_auto_generated_name : $this->is_auto_generated_name;
        $this->high_priority = ($message->high_priority !== null) ? $message->high_priority : $this->high_priority;
        $this->persona_set_by_user = ($message->persona_set_by_user !== null) ? $message->persona_set_by_user : $this->persona_set_by_user;
        $this->persona_state_flags = ($message->persona_state_flags !== null) ? $message->persona_state_flags : $this->persona_state_flags;
    }


}

