<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : tf/steamdatagram_messages.proto
 */


namespace SteamKit\Base\GC\TF2\SteamDatagramMsg;

/**
 * Protobuf enum : SteamKit.Base.GC.TF2.SteamDatagramMsg.ESteamDatagramMsgID
 */
class ESteamDatagramMsgID extends \Protobuf\Enum
{

    /**
     * k_ESteamDatagramMsg_Invalid = 0
     */
    const k_ESteamDatagramMsg_Invalid_VALUE = 0;

    /**
     * k_ESteamDatagramMsg_RouterPingRequest = 1
     */
    const k_ESteamDatagramMsg_RouterPingRequest_VALUE = 1;

    /**
     * k_ESteamDatagramMsg_RouterPingReply = 2
     */
    const k_ESteamDatagramMsg_RouterPingReply_VALUE = 2;

    /**
     * k_ESteamDatagramMsg_GameserverPingRequest = 3
     */
    const k_ESteamDatagramMsg_GameserverPingRequest_VALUE = 3;

    /**
     * k_ESteamDatagramMsg_GameserverPingReply = 4
     */
    const k_ESteamDatagramMsg_GameserverPingReply_VALUE = 4;

    /**
     * k_ESteamDatagramMsg_GameserverSessionRequest = 5
     */
    const k_ESteamDatagramMsg_GameserverSessionRequest_VALUE = 5;

    /**
     * k_ESteamDatagramMsg_GameserverSessionEstablished = 6
     */
    const k_ESteamDatagramMsg_GameserverSessionEstablished_VALUE = 6;

    /**
     * k_ESteamDatagramMsg_NoSession = 7
     */
    const k_ESteamDatagramMsg_NoSession_VALUE = 7;

    /**
     * k_ESteamDatagramMsg_Diagnostic = 8
     */
    const k_ESteamDatagramMsg_Diagnostic_VALUE = 8;

    /**
     * k_ESteamDatagramMsg_DataClientToRouter = 9
     */
    const k_ESteamDatagramMsg_DataClientToRouter_VALUE = 9;

    /**
     * k_ESteamDatagramMsg_DataRouterToServer = 10
     */
    const k_ESteamDatagramMsg_DataRouterToServer_VALUE = 10;

    /**
     * k_ESteamDatagramMsg_DataServerToRouter = 11
     */
    const k_ESteamDatagramMsg_DataServerToRouter_VALUE = 11;

    /**
     * k_ESteamDatagramMsg_DataRouterToClient = 12
     */
    const k_ESteamDatagramMsg_DataRouterToClient_VALUE = 12;

    /**
     * k_ESteamDatagramMsg_Stats = 13
     */
    const k_ESteamDatagramMsg_Stats_VALUE = 13;

    /**
     * k_ESteamDatagramMsg_ClientPingSampleRequest = 14
     */
    const k_ESteamDatagramMsg_ClientPingSampleRequest_VALUE = 14;

    /**
     * k_ESteamDatagramMsg_ClientPingSampleReply = 15
     */
    const k_ESteamDatagramMsg_ClientPingSampleReply_VALUE = 15;

    /**
     * k_ESteamDatagramMsg_ClientToRouterSwitchedPrimary = 16
     */
    const k_ESteamDatagramMsg_ClientToRouterSwitchedPrimary_VALUE = 16;

    /**
     * k_ESteamDatagramMsg_RelayHealth = 17
     */
    const k_ESteamDatagramMsg_RelayHealth_VALUE = 17;

    /**
     * @var \SteamKit\Base\GC\TF2\SteamDatagramMsg\ESteamDatagramMsgID
     */
    protected static $k_ESteamDatagramMsg_Invalid = null;

    /**
     * @var \SteamKit\Base\GC\TF2\SteamDatagramMsg\ESteamDatagramMsgID
     */
    protected static $k_ESteamDatagramMsg_RouterPingRequest = null;

    /**
     * @var \SteamKit\Base\GC\TF2\SteamDatagramMsg\ESteamDatagramMsgID
     */
    protected static $k_ESteamDatagramMsg_RouterPingReply = null;

    /**
     * @var \SteamKit\Base\GC\TF2\SteamDatagramMsg\ESteamDatagramMsgID
     */
    protected static $k_ESteamDatagramMsg_GameserverPingRequest = null;

    /**
     * @var \SteamKit\Base\GC\TF2\SteamDatagramMsg\ESteamDatagramMsgID
     */
    protected static $k_ESteamDatagramMsg_GameserverPingReply = null;

    /**
     * @var \SteamKit\Base\GC\TF2\SteamDatagramMsg\ESteamDatagramMsgID
     */
    protected static $k_ESteamDatagramMsg_GameserverSessionRequest = null;

    /**
     * @var \SteamKit\Base\GC\TF2\SteamDatagramMsg\ESteamDatagramMsgID
     */
    protected static $k_ESteamDatagramMsg_GameserverSessionEstablished = null;

    /**
     * @var \SteamKit\Base\GC\TF2\SteamDatagramMsg\ESteamDatagramMsgID
     */
    protected static $k_ESteamDatagramMsg_NoSession = null;

    /**
     * @var \SteamKit\Base\GC\TF2\SteamDatagramMsg\ESteamDatagramMsgID
     */
    protected static $k_ESteamDatagramMsg_Diagnostic = null;

    /**
     * @var \SteamKit\Base\GC\TF2\SteamDatagramMsg\ESteamDatagramMsgID
     */
    protected static $k_ESteamDatagramMsg_DataClientToRouter = null;

    /**
     * @var \SteamKit\Base\GC\TF2\SteamDatagramMsg\ESteamDatagramMsgID
     */
    protected static $k_ESteamDatagramMsg_DataRouterToServer = null;

    /**
     * @var \SteamKit\Base\GC\TF2\SteamDatagramMsg\ESteamDatagramMsgID
     */
    protected static $k_ESteamDatagramMsg_DataServerToRouter = null;

    /**
     * @var \SteamKit\Base\GC\TF2\SteamDatagramMsg\ESteamDatagramMsgID
     */
    protected static $k_ESteamDatagramMsg_DataRouterToClient = null;

    /**
     * @var \SteamKit\Base\GC\TF2\SteamDatagramMsg\ESteamDatagramMsgID
     */
    protected static $k_ESteamDatagramMsg_Stats = null;

    /**
     * @var \SteamKit\Base\GC\TF2\SteamDatagramMsg\ESteamDatagramMsgID
     */
    protected static $k_ESteamDatagramMsg_ClientPingSampleRequest = null;

    /**
     * @var \SteamKit\Base\GC\TF2\SteamDatagramMsg\ESteamDatagramMsgID
     */
    protected static $k_ESteamDatagramMsg_ClientPingSampleReply = null;

    /**
     * @var \SteamKit\Base\GC\TF2\SteamDatagramMsg\ESteamDatagramMsgID
     */
    protected static $k_ESteamDatagramMsg_ClientToRouterSwitchedPrimary = null;

    /**
     * @var \SteamKit\Base\GC\TF2\SteamDatagramMsg\ESteamDatagramMsgID
     */
    protected static $k_ESteamDatagramMsg_RelayHealth = null;

    /**
     * @return \SteamKit\Base\GC\TF2\SteamDatagramMsg\ESteamDatagramMsgID
     */
    public static function k_ESteamDatagramMsg_Invalid()
    {
        if (self::$k_ESteamDatagramMsg_Invalid !== null) {
            return self::$k_ESteamDatagramMsg_Invalid;
        }

        return self::$k_ESteamDatagramMsg_Invalid = new self('k_ESteamDatagramMsg_Invalid', self::k_ESteamDatagramMsg_Invalid_VALUE);
    }

    /**
     * @return \SteamKit\Base\GC\TF2\SteamDatagramMsg\ESteamDatagramMsgID
     */
    public static function k_ESteamDatagramMsg_RouterPingRequest()
    {
        if (self::$k_ESteamDatagramMsg_RouterPingRequest !== null) {
            return self::$k_ESteamDatagramMsg_RouterPingRequest;
        }

        return self::$k_ESteamDatagramMsg_RouterPingRequest = new self('k_ESteamDatagramMsg_RouterPingRequest', self::k_ESteamDatagramMsg_RouterPingRequest_VALUE);
    }

    /**
     * @return \SteamKit\Base\GC\TF2\SteamDatagramMsg\ESteamDatagramMsgID
     */
    public static function k_ESteamDatagramMsg_RouterPingReply()
    {
        if (self::$k_ESteamDatagramMsg_RouterPingReply !== null) {
            return self::$k_ESteamDatagramMsg_RouterPingReply;
        }

        return self::$k_ESteamDatagramMsg_RouterPingReply = new self('k_ESteamDatagramMsg_RouterPingReply', self::k_ESteamDatagramMsg_RouterPingReply_VALUE);
    }

    /**
     * @return \SteamKit\Base\GC\TF2\SteamDatagramMsg\ESteamDatagramMsgID
     */
    public static function k_ESteamDatagramMsg_GameserverPingRequest()
    {
        if (self::$k_ESteamDatagramMsg_GameserverPingRequest !== null) {
            return self::$k_ESteamDatagramMsg_GameserverPingRequest;
        }

        return self::$k_ESteamDatagramMsg_GameserverPingRequest = new self('k_ESteamDatagramMsg_GameserverPingRequest', self::k_ESteamDatagramMsg_GameserverPingRequest_VALUE);
    }

    /**
     * @return \SteamKit\Base\GC\TF2\SteamDatagramMsg\ESteamDatagramMsgID
     */
    public static function k_ESteamDatagramMsg_GameserverPingReply()
    {
        if (self::$k_ESteamDatagramMsg_GameserverPingReply !== null) {
            return self::$k_ESteamDatagramMsg_GameserverPingReply;
        }

        return self::$k_ESteamDatagramMsg_GameserverPingReply = new self('k_ESteamDatagramMsg_GameserverPingReply', self::k_ESteamDatagramMsg_GameserverPingReply_VALUE);
    }

    /**
     * @return \SteamKit\Base\GC\TF2\SteamDatagramMsg\ESteamDatagramMsgID
     */
    public static function k_ESteamDatagramMsg_GameserverSessionRequest()
    {
        if (self::$k_ESteamDatagramMsg_GameserverSessionRequest !== null) {
            return self::$k_ESteamDatagramMsg_GameserverSessionRequest;
        }

        return self::$k_ESteamDatagramMsg_GameserverSessionRequest = new self('k_ESteamDatagramMsg_GameserverSessionRequest', self::k_ESteamDatagramMsg_GameserverSessionRequest_VALUE);
    }

    /**
     * @return \SteamKit\Base\GC\TF2\SteamDatagramMsg\ESteamDatagramMsgID
     */
    public static function k_ESteamDatagramMsg_GameserverSessionEstablished()
    {
        if (self::$k_ESteamDatagramMsg_GameserverSessionEstablished !== null) {
            return self::$k_ESteamDatagramMsg_GameserverSessionEstablished;
        }

        return self::$k_ESteamDatagramMsg_GameserverSessionEstablished = new self('k_ESteamDatagramMsg_GameserverSessionEstablished', self::k_ESteamDatagramMsg_GameserverSessionEstablished_VALUE);
    }

    /**
     * @return \SteamKit\Base\GC\TF2\SteamDatagramMsg\ESteamDatagramMsgID
     */
    public static function k_ESteamDatagramMsg_NoSession()
    {
        if (self::$k_ESteamDatagramMsg_NoSession !== null) {
            return self::$k_ESteamDatagramMsg_NoSession;
        }

        return self::$k_ESteamDatagramMsg_NoSession = new self('k_ESteamDatagramMsg_NoSession', self::k_ESteamDatagramMsg_NoSession_VALUE);
    }

    /**
     * @return \SteamKit\Base\GC\TF2\SteamDatagramMsg\ESteamDatagramMsgID
     */
    public static function k_ESteamDatagramMsg_Diagnostic()
    {
        if (self::$k_ESteamDatagramMsg_Diagnostic !== null) {
            return self::$k_ESteamDatagramMsg_Diagnostic;
        }

        return self::$k_ESteamDatagramMsg_Diagnostic = new self('k_ESteamDatagramMsg_Diagnostic', self::k_ESteamDatagramMsg_Diagnostic_VALUE);
    }

    /**
     * @return \SteamKit\Base\GC\TF2\SteamDatagramMsg\ESteamDatagramMsgID
     */
    public static function k_ESteamDatagramMsg_DataClientToRouter()
    {
        if (self::$k_ESteamDatagramMsg_DataClientToRouter !== null) {
            return self::$k_ESteamDatagramMsg_DataClientToRouter;
        }

        return self::$k_ESteamDatagramMsg_DataClientToRouter = new self('k_ESteamDatagramMsg_DataClientToRouter', self::k_ESteamDatagramMsg_DataClientToRouter_VALUE);
    }

    /**
     * @return \SteamKit\Base\GC\TF2\SteamDatagramMsg\ESteamDatagramMsgID
     */
    public static function k_ESteamDatagramMsg_DataRouterToServer()
    {
        if (self::$k_ESteamDatagramMsg_DataRouterToServer !== null) {
            return self::$k_ESteamDatagramMsg_DataRouterToServer;
        }

        return self::$k_ESteamDatagramMsg_DataRouterToServer = new self('k_ESteamDatagramMsg_DataRouterToServer', self::k_ESteamDatagramMsg_DataRouterToServer_VALUE);
    }

    /**
     * @return \SteamKit\Base\GC\TF2\SteamDatagramMsg\ESteamDatagramMsgID
     */
    public static function k_ESteamDatagramMsg_DataServerToRouter()
    {
        if (self::$k_ESteamDatagramMsg_DataServerToRouter !== null) {
            return self::$k_ESteamDatagramMsg_DataServerToRouter;
        }

        return self::$k_ESteamDatagramMsg_DataServerToRouter = new self('k_ESteamDatagramMsg_DataServerToRouter', self::k_ESteamDatagramMsg_DataServerToRouter_VALUE);
    }

    /**
     * @return \SteamKit\Base\GC\TF2\SteamDatagramMsg\ESteamDatagramMsgID
     */
    public static function k_ESteamDatagramMsg_DataRouterToClient()
    {
        if (self::$k_ESteamDatagramMsg_DataRouterToClient !== null) {
            return self::$k_ESteamDatagramMsg_DataRouterToClient;
        }

        return self::$k_ESteamDatagramMsg_DataRouterToClient = new self('k_ESteamDatagramMsg_DataRouterToClient', self::k_ESteamDatagramMsg_DataRouterToClient_VALUE);
    }

    /**
     * @return \SteamKit\Base\GC\TF2\SteamDatagramMsg\ESteamDatagramMsgID
     */
    public static function k_ESteamDatagramMsg_Stats()
    {
        if (self::$k_ESteamDatagramMsg_Stats !== null) {
            return self::$k_ESteamDatagramMsg_Stats;
        }

        return self::$k_ESteamDatagramMsg_Stats = new self('k_ESteamDatagramMsg_Stats', self::k_ESteamDatagramMsg_Stats_VALUE);
    }

    /**
     * @return \SteamKit\Base\GC\TF2\SteamDatagramMsg\ESteamDatagramMsgID
     */
    public static function k_ESteamDatagramMsg_ClientPingSampleRequest()
    {
        if (self::$k_ESteamDatagramMsg_ClientPingSampleRequest !== null) {
            return self::$k_ESteamDatagramMsg_ClientPingSampleRequest;
        }

        return self::$k_ESteamDatagramMsg_ClientPingSampleRequest = new self('k_ESteamDatagramMsg_ClientPingSampleRequest', self::k_ESteamDatagramMsg_ClientPingSampleRequest_VALUE);
    }

    /**
     * @return \SteamKit\Base\GC\TF2\SteamDatagramMsg\ESteamDatagramMsgID
     */
    public static function k_ESteamDatagramMsg_ClientPingSampleReply()
    {
        if (self::$k_ESteamDatagramMsg_ClientPingSampleReply !== null) {
            return self::$k_ESteamDatagramMsg_ClientPingSampleReply;
        }

        return self::$k_ESteamDatagramMsg_ClientPingSampleReply = new self('k_ESteamDatagramMsg_ClientPingSampleReply', self::k_ESteamDatagramMsg_ClientPingSampleReply_VALUE);
    }

    /**
     * @return \SteamKit\Base\GC\TF2\SteamDatagramMsg\ESteamDatagramMsgID
     */
    public static function k_ESteamDatagramMsg_ClientToRouterSwitchedPrimary()
    {
        if (self::$k_ESteamDatagramMsg_ClientToRouterSwitchedPrimary !== null) {
            return self::$k_ESteamDatagramMsg_ClientToRouterSwitchedPrimary;
        }

        return self::$k_ESteamDatagramMsg_ClientToRouterSwitchedPrimary = new self('k_ESteamDatagramMsg_ClientToRouterSwitchedPrimary', self::k_ESteamDatagramMsg_ClientToRouterSwitchedPrimary_VALUE);
    }

    /**
     * @return \SteamKit\Base\GC\TF2\SteamDatagramMsg\ESteamDatagramMsgID
     */
    public static function k_ESteamDatagramMsg_RelayHealth()
    {
        if (self::$k_ESteamDatagramMsg_RelayHealth !== null) {
            return self::$k_ESteamDatagramMsg_RelayHealth;
        }

        return self::$k_ESteamDatagramMsg_RelayHealth = new self('k_ESteamDatagramMsg_RelayHealth', self::k_ESteamDatagramMsg_RelayHealth_VALUE);
    }

    /**
     * @param int $value
     * @return \SteamKit\Base\GC\TF2\SteamDatagramMsg\ESteamDatagramMsgID
     */
    public static function valueOf($value)
    {
        switch ($value) {
            case 0: return self::k_ESteamDatagramMsg_Invalid();
            case 1: return self::k_ESteamDatagramMsg_RouterPingRequest();
            case 2: return self::k_ESteamDatagramMsg_RouterPingReply();
            case 3: return self::k_ESteamDatagramMsg_GameserverPingRequest();
            case 4: return self::k_ESteamDatagramMsg_GameserverPingReply();
            case 5: return self::k_ESteamDatagramMsg_GameserverSessionRequest();
            case 6: return self::k_ESteamDatagramMsg_GameserverSessionEstablished();
            case 7: return self::k_ESteamDatagramMsg_NoSession();
            case 8: return self::k_ESteamDatagramMsg_Diagnostic();
            case 9: return self::k_ESteamDatagramMsg_DataClientToRouter();
            case 10: return self::k_ESteamDatagramMsg_DataRouterToServer();
            case 11: return self::k_ESteamDatagramMsg_DataServerToRouter();
            case 12: return self::k_ESteamDatagramMsg_DataRouterToClient();
            case 13: return self::k_ESteamDatagramMsg_Stats();
            case 14: return self::k_ESteamDatagramMsg_ClientPingSampleRequest();
            case 15: return self::k_ESteamDatagramMsg_ClientPingSampleReply();
            case 16: return self::k_ESteamDatagramMsg_ClientToRouterSwitchedPrimary();
            case 17: return self::k_ESteamDatagramMsg_RelayHealth();
            default: return null;
        }
    }


}

