<?php

namespace SteamKit\Base\Enums;

class EMsg
{
	const Invalid = 0;
	const Multi = 1;
	const ProtobufWrapped = 2;
	const BaseGeneral = 100;
	const GenericReply = 100;
	const DestJobFailed = 113;
	const Alert = 115;
	const SCIDRequest = 120;
	const SCIDResponse = 121;
	const JobHeartbeat = 123;
	const HubConnect = 124;
	const Subscribe = 126;
	const RouteMessage = 127; // obsolete
	const RemoteSysID = 128; // obsolete
	const AMCreateAccountResponse = 129;
	const WGRequest = 130;
	const WGResponse = 131;
	const KeepAlive = 132;
	const WebAPIJobRequest = 133;
	const WebAPIJobResponse = 134;
	const ClientSessionStart = 135;
	const ClientSessionEnd = 136;
	const ClientSessionUpdateAuthTicket = 137; // obsolete "renamed to ClientSessionUpdate"
	const ClientSessionUpdate = 137;
	const StatsDeprecated = 138; // obsolete
	const Ping = 139;
	const PingResponse = 140;
	const Stats = 141;
	const RequestFullStatsBlock = 142;
	const LoadDBOCacheItem = 143;
	const LoadDBOCacheItemResponse = 144;
	const InvalidateDBOCacheItems = 145;
	const ServiceMethod = 146;
	const ServiceMethodResponse = 147;
	const ClientPackageVersions = 148;
	const TimestampRequest = 149;
	const TimestampResponse = 150;
	const BaseShell = 200;
	const AssignSysID = 200;
	const Exit = 201;
	const DirRequest = 202;
	const DirResponse = 203;
	const ZipRequest = 204;
	const ZipResponse = 205;
	const UpdateRecordResponse = 215;
	const UpdateCreditCardRequest = 221;
	const UpdateUserBanResponse = 225;
	const PrepareToExit = 226;
	const ContentDescriptionUpdate = 227;
	const TestResetServer = 228;
	const UniverseChanged = 229;
	const ShellConfigInfoUpdate = 230;
	const RequestWindowsEventLogEntries = 233;
	const ProvideWindowsEventLogEntries = 234;
	const ShellSearchLogs = 235;
	const ShellSearchLogsResponse = 236;
	const ShellCheckWindowsUpdates = 237;
	const ShellCheckWindowsUpdatesResponse = 238;
	const ShellFlushUserLicenseCache = 239; // obsolete
	const BaseGM = 300;
	const Heartbeat = 300;
	const ShellFailed = 301;
	const ExitShells = 307;
	const ExitShell = 308;
	const GracefulExitShell = 309;
	const NotifyWatchdog = 314;
	const LicenseProcessingComplete = 316;
	const SetTestFlag = 317;
	const QueuedEmailsComplete = 318;
	const GMReportPHPError = 319;
	const GMDRMSync = 320;
	const PhysicalBoxInventory = 321;
	const UpdateConfigFile = 322;
	const TestInitDB = 323;
	const GMWriteConfigToSQL = 324;
	const GMLoadActivationCodes = 325;
	const GMQueueForFBS = 326;
	const GMSchemaConversionResults = 327;
	const GMSchemaConversionResultsResponse = 328; // obsolete
	const GMWriteShellFailureToSQL = 329;
	const GMWriteStatsToSOS = 330;
	const GMGetServiceMethodRouting = 331;
	const GMGetServiceMethodRoutingResponse = 332;
	const GMConvertUserWallets = 333;
	const BaseAIS = 400;
	const AISRefreshContentDescription = 401; // obsolete
	const AISRequestContentDescription = 402;
	const AISUpdateAppInfo = 403;
	const AISUpdatePackageInfo = 404; // obsolete "renamed to AISUpdatePackageCosts"
	const AISUpdatePackageCosts = 404;
	const AISGetPackageChangeNumber = 405;
	const AISGetPackageChangeNumberResponse = 406;
	const AISAppInfoTableChanged = 407; // obsolete
	const AISUpdatePackageCostsResponse = 408;
	const AISCreateMarketingMessage = 409;
	const AISCreateMarketingMessageResponse = 410;
	const AISGetMarketingMessage = 411;
	const AISGetMarketingMessageResponse = 412;
	const AISUpdateMarketingMessage = 413;
	const AISUpdateMarketingMessageResponse = 414;
	const AISRequestMarketingMessageUpdate = 415;
	const AISDeleteMarketingMessage = 416;
	const AISGetMarketingTreatments = 419; // obsolete
	const AISGetMarketingTreatmentsResponse = 420; // obsolete
	const AISRequestMarketingTreatmentUpdate = 421; // obsolete
	const AISTestAddPackage = 422; // obsolete
	const AIGetAppGCFlags = 423;
	const AIGetAppGCFlagsResponse = 424;
	const AIGetAppList = 425;
	const AIGetAppListResponse = 426;
	const AIGetAppInfo = 427; // obsolete
	const AIGetAppInfoResponse = 428; // obsolete
	const AISGetCouponDefinition = 429;
	const AISGetCouponDefinitionResponse = 430;
	const AISUpdateSlaveContentDescription = 431;
	const AISUpdateSlaveContentDescriptionResponse = 432;
	const AISTestEnableGC = 433;
	const BaseAM = 500;
	const AMUpdateUserBanRequest = 504;
	const AMAddLicense = 505;
	const AMBeginProcessingLicenses = 507; // obsolete
	const AMSendSystemIMToUser = 508;
	const AMExtendLicense = 509;
	const AMAddMinutesToLicense = 510;
	const AMCancelLicense = 511;
	const AMInitPurchase = 512;
	const AMPurchaseResponse = 513;
	const AMGetFinalPrice = 514;
	const AMGetFinalPriceResponse = 515;
	const AMGetLegacyGameKey = 516;
	const AMGetLegacyGameKeyResponse = 517;
	const AMFindHungTransactions = 518;
	const AMSetAccountTrustedRequest = 519;
	const AMCompletePurchase = 521;
	const AMCancelPurchase = 522;
	const AMNewChallenge = 523;
	const AMLoadOEMTickets = 524;
	const AMFixPendingPurchase = 525;
	const AMFixPendingPurchaseResponse = 526;
	const AMIsUserBanned = 527;
	const AMRegisterKey = 528;
	const AMLoadActivationCodes = 529;
	const AMLoadActivationCodesResponse = 530;
	const AMLookupKeyResponse = 531;
	const AMLookupKey = 532;
	const AMChatCleanup = 533;
	const AMClanCleanup = 534;
	const AMFixPendingRefund = 535;
	const AMReverseChargeback = 536;
	const AMReverseChargebackResponse = 537;
	const AMClanCleanupList = 538;
	const AMGetLicenses = 539;
	const AMGetLicensesResponse = 540;
	const AllowUserToPlayQuery = 550;
	const AllowUserToPlayResponse = 551;
	const AMVerfiyUser = 552;
	const AMClientNotPlaying = 553;
	const ClientRequestFriendship = 554;
	const AMRelayPublishStatus = 555;
	const AMResetCommunityContent = 556; // obsolete
	const AMPrimePersonaStateCache = 557; // obsolete
	const AMAllowUserContentQuery = 558; // obsolete
	const AMAllowUserContentResponse = 559; // obsolete
	const AMInitPurchaseResponse = 560;
	const AMRevokePurchaseResponse = 561;
	const AMLockProfile = 562; // obsolete
	const AMRefreshGuestPasses = 563;
	const AMInviteUserToClan = 564;
	const AMAcknowledgeClanInvite = 565;
	const AMGrantGuestPasses = 566;
	const AMClanDataUpdated = 567;
	const AMReloadAccount = 568;
	const AMClientChatMsgRelay = 569;
	const AMChatMulti = 570;
	const AMClientChatInviteRelay = 571;
	const AMChatInvite = 572;
	const AMClientJoinChatRelay = 573;
	const AMClientChatMemberInfoRelay = 574;
	const AMPublishChatMemberInfo = 575;
	const AMClientAcceptFriendInvite = 576;
	const AMChatEnter = 577;
	const AMClientPublishRemovalFromSource = 578;
	const AMChatActionResult = 579;
	const AMFindAccounts = 580;
	const AMFindAccountsResponse = 581;
	const AMRequestAccountData = 582;
	const AMRequestAccountDataResponse = 583;
	const AMSetAccountFlags = 584;
	const AMCreateClan = 586;
	const AMCreateClanResponse = 587;
	const AMGetClanDetails = 588;
	const AMGetClanDetailsResponse = 589;
	const AMSetPersonaName = 590;
	const AMSetAvatar = 591;
	const AMAuthenticateUser = 592;
	const AMAuthenticateUserResponse = 593;
	const AMGetAccountFriendsCount = 594; // obsolete
	const AMGetAccountFriendsCountResponse = 595; // obsolete
	const AMP2PIntroducerMessage = 596;
	const ClientChatAction = 597;
	const AMClientChatActionRelay = 598;
	const BaseVS = 600;
	const ReqChallenge = 600;
	const VACResponse = 601;
	const ReqChallengeTest = 602;
	const VSMarkCheat = 604;
	const VSAddCheat = 605;
	const VSPurgeCodeModDB = 606;
	const VSGetChallengeResults = 607;
	const VSChallengeResultText = 608;
	const VSReportLingerer = 609;
	const VSRequestManagedChallenge = 610;
	const VSLoadDBFinished = 611;
	const BaseDRMS = 625;
	const DRMBuildBlobRequest = 628;
	const DRMBuildBlobResponse = 629;
	const DRMResolveGuidRequest = 630;
	const DRMResolveGuidResponse = 631;
	const DRMVariabilityReport = 633;
	const DRMVariabilityReportResponse = 634;
	const DRMStabilityReport = 635;
	const DRMStabilityReportResponse = 636;
	const DRMDetailsReportRequest = 637;
	const DRMDetailsReportResponse = 638;
	const DRMProcessFile = 639;
	const DRMAdminUpdate = 640;
	const DRMAdminUpdateResponse = 641;
	const DRMSync = 642;
	const DRMSyncResponse = 643;
	const DRMProcessFileResponse = 644;
	const DRMEmptyGuidCache = 645;
	const DRMEmptyGuidCacheResponse = 646;
	const BaseCS = 650;
	const CSUserContentRequest = 652; // obsolete
	const BaseClient = 700;
	const ClientLogOn_Deprecated = 701; // obsolete
	const ClientAnonLogOn_Deprecated = 702; // obsolete
	const ClientHeartBeat = 703;
	const ClientVACResponse = 704;
	const ClientGamesPlayed_obsolete = 705; // obsolete
	const ClientLogOff = 706;
	const ClientNoUDPConnectivity = 707;
	const ClientInformOfCreateAccount = 708;
	const ClientAckVACBan = 709;
	const ClientConnectionStats = 710;
	const ClientInitPurchase = 711; // obsolete
	const ClientPingResponse = 712;
	const ClientRemoveFriend = 714;
	const ClientGamesPlayedNoDataBlob = 715;
	const ClientChangeStatus = 716;
	const ClientVacStatusResponse = 717;
	const ClientFriendMsg = 718;
	const ClientGameConnect_obsolete = 719; // obsolete
	const ClientGamesPlayed2_obsolete = 720; // obsolete
	const ClientGameEnded_obsolete = 721; // obsolete
	const ClientGetFinalPrice = 722; // obsolete
	const ClientSystemIM = 726;
	const ClientSystemIMAck = 727;
	const ClientGetLicenses = 728;
	const ClientCancelLicense = 729; // obsolete
	const ClientGetLegacyGameKey = 730;
	const ClientContentServerLogOn_Deprecated = 731; // obsolete
	const ClientAckVACBan2 = 732;
	const ClientAckMessageByGID = 735; // obsolete
	const ClientGetPurchaseReceipts = 736;
	const ClientAckPurchaseReceipt = 737; // obsolete
	const ClientGamesPlayed3_obsolete = 738; // obsolete
	const ClientSendGuestPass = 739; // obsolete
	const ClientAckGuestPass = 740;
	const ClientRedeemGuestPass = 741;
	const ClientGamesPlayed = 742;
	const ClientRegisterKey = 743;
	const ClientInviteUserToClan = 744;
	const ClientAcknowledgeClanInvite = 745;
	const ClientPurchaseWithMachineID = 746;
	const ClientAppUsageEvent = 747;
	const ClientGetGiftTargetList = 748; // obsolete
	const ClientGetGiftTargetListResponse = 749; // obsolete
	const ClientLogOnResponse = 751;
	const ClientVACChallenge = 753;
	const ClientSetHeartbeatRate = 755;
	const ClientNotLoggedOnDeprecated = 756; // obsolete
	const ClientLoggedOff = 757;
	const GSApprove = 758;
	const GSDeny = 759;
	const GSKick = 760;
	const ClientCreateAcctResponse = 761;
	const ClientPurchaseResponse = 763;
	const ClientPing = 764;
	const ClientNOP = 765;
	const ClientPersonaState = 766;
	const ClientFriendsList = 767;
	const ClientAccountInfo = 768;
	const ClientVacStatusQuery = 770;
	const ClientNewsUpdate = 771;
	const ClientGameConnectDeny = 773;
	const GSStatusReply = 774;
	const ClientGetFinalPriceResponse = 775; // obsolete
	const ClientGameConnectTokens = 779;
	const ClientLicenseList = 780;
	const ClientCancelLicenseResponse = 781; // obsolete
	const ClientVACBanStatus = 782;
	const ClientCMList = 783;
	const ClientEncryptPct = 784;
	const ClientGetLegacyGameKeyResponse = 785;
	const ClientFavoritesList = 786; // obsolete
	const CSUserContentApprove = 787; // obsolete
	const CSUserContentDeny = 788; // obsolete
	const ClientInitPurchaseResponse = 789; // obsolete
	const ClientAddFriend = 791;
	const ClientAddFriendResponse = 792;
	const ClientInviteFriend = 793; // obsolete
	const ClientInviteFriendResponse = 794; // obsolete
	const ClientSendGuestPassResponse = 795; // obsolete
	const ClientAckGuestPassResponse = 796;
	const ClientRedeemGuestPassResponse = 797;
	const ClientUpdateGuestPassesList = 798;
	const ClientChatMsg = 799;
	const ClientChatInvite = 800;
	const ClientJoinChat = 801;
	const ClientChatMemberInfo = 802;
	const ClientLogOnWithCredentials_Deprecated = 803; // obsolete
	const ClientPasswordChangeResponse = 805;
	const ClientChatEnter = 807;
	const ClientFriendRemovedFromSource = 808;
	const ClientCreateChat = 809;
	const ClientCreateChatResponse = 810;
	const ClientUpdateChatMetadata = 811; // obsolete
	const ClientP2PIntroducerMessage = 813;
	const ClientChatActionResult = 814;
	const ClientRequestFriendData = 815;
	const ClientGetUserStats = 818;
	const ClientGetUserStatsResponse = 819;
	const ClientStoreUserStats = 820;
	const ClientStoreUserStatsResponse = 821;
	const ClientClanState = 822;
	const ClientServiceModule = 830;
	const ClientServiceCall = 831;
	const ClientServiceCallResponse = 832;
	const ClientPackageInfoRequest = 833;
	const ClientPackageInfoResponse = 834;
	const ClientNatTraversalStatEvent = 839;
	const ClientAppInfoRequest = 840;
	const ClientAppInfoResponse = 841;
	const ClientSteamUsageEvent = 842;
	const ClientCheckPassword = 845;
	const ClientResetPassword = 846;
	const ClientCheckPasswordResponse = 848;
	const ClientResetPasswordResponse = 849;
	const ClientSessionToken = 850;
	const ClientDRMProblemReport = 851;
	const ClientSetIgnoreFriend = 855;
	const ClientSetIgnoreFriendResponse = 856;
	const ClientGetAppOwnershipTicket = 857;
	const ClientGetAppOwnershipTicketResponse = 858;
	const ClientGetLobbyListResponse = 860;
	const ClientGetLobbyMetadata = 861; // obsolete
	const ClientGetLobbyMetadataResponse = 862; // obsolete
	const ClientVTTCert = 863;
	const ClientAppInfoUpdate = 866;
	const ClientAppInfoChanges = 867;
	const ClientServerList = 880;
	const ClientEmailChangeResponse = 891;
	const ClientSecretQAChangeResponse = 892;
	const ClientDRMBlobRequest = 896;
	const ClientDRMBlobResponse = 897;
	const ClientLookupKey = 898; // obsolete
	const ClientLookupKeyResponse = 899; // obsolete
	const BaseGameServer = 900;
	const GSDisconnectNotice = 901;
	const GSStatus = 903;
	const GSUserPlaying = 905;
	const GSStatus2 = 906;
	const GSStatusUpdate_Unused = 907;
	const GSServerType = 908;
	const GSPlayerList = 909;
	const GSGetUserAchievementStatus = 910;
	const GSGetUserAchievementStatusResponse = 911;
	const GSGetPlayStats = 918;
	const GSGetPlayStatsResponse = 919;
	const GSGetUserGroupStatus = 920;
	const AMGetUserGroupStatus = 921;
	const AMGetUserGroupStatusResponse = 922;
	const GSGetUserGroupStatusResponse = 923;
	const GSGetReputation = 936;
	const GSGetReputationResponse = 937;
	const GSAssociateWithClan = 938;
	const GSAssociateWithClanResponse = 939;
	const GSComputeNewPlayerCompatibility = 940;
	const GSComputeNewPlayerCompatibilityResponse = 941;
	const BaseAdmin = 1000;
	const AdminCmd = 1000;
	const AdminCmdResponse = 1004;
	const AdminLogListenRequest = 1005;
	const AdminLogEvent = 1006;
	const LogSearchRequest = 1007; // obsolete
	const LogSearchResponse = 1008; // obsolete
	const LogSearchCancel = 1009; // obsolete
	const UniverseData = 1010;
	const RequestStatHistory = 1014; // obsolete
	const StatHistory = 1015; // obsolete
	const AdminPwLogon = 1017; // obsolete
	const AdminPwLogonResponse = 1018; // obsolete
	const AdminSpew = 1019;
	const AdminConsoleTitle = 1020;
	const AdminGCSpew = 1023;
	const AdminGCCommand = 1024;
	const AdminGCGetCommandList = 1025;
	const AdminGCGetCommandListResponse = 1026;
	const FBSConnectionData = 1027;
	const AdminMsgSpew = 1028;
	const BaseFBS = 1100;
	const FBSReqVersion = 1100;
	const FBSVersionInfo = 1101;
	const FBSForceRefresh = 1102;
	const FBSForceBounce = 1103;
	const FBSDeployPackage = 1104;
	const FBSDeployResponse = 1105;
	const FBSUpdateBootstrapper = 1106;
	const FBSSetState = 1107;
	const FBSApplyOSUpdates = 1108;
	const FBSRunCMDScript = 1109;
	const FBSRebootBox = 1110;
	const FBSSetBigBrotherMode = 1111;
	const FBSMinidumpServer = 1112;
	const FBSSetShellCount_obsolete = 1113; // obsolete
	const FBSDeployHotFixPackage = 1114;
	const FBSDeployHotFixResponse = 1115;
	const FBSDownloadHotFix = 1116;
	const FBSDownloadHotFixResponse = 1117;
	const FBSUpdateTargetConfigFile = 1118;
	const FBSApplyAccountCred = 1119;
	const FBSApplyAccountCredResponse = 1120;
	const FBSSetShellCount = 1121;
	const FBSTerminateShell = 1122;
	const FBSQueryGMForRequest = 1123;
	const FBSQueryGMResponse = 1124;
	const FBSTerminateZombies = 1125;
	const FBSInfoFromBootstrapper = 1126;
	const FBSRebootBoxResponse = 1127;
	const FBSBootstrapperPackageRequest = 1128;
	const FBSBootstrapperPackageResponse = 1129;
	const FBSBootstrapperGetPackageChunk = 1130;
	const FBSBootstrapperGetPackageChunkResponse = 1131;
	const FBSBootstrapperPackageTransferProgress = 1132;
	const FBSRestartBootstrapper = 1133;
	const BaseFileXfer = 1200;
	const FileXferRequest = 1200;
	const FileXferResponse = 1201;
	const FileXferData = 1202;
	const FileXferEnd = 1203;
	const FileXferDataAck = 1204;
	const BaseChannelAuth = 1300;
	const ChannelAuthChallenge = 1300;
	const ChannelAuthResponse = 1301;
	const ChannelAuthResult = 1302;
	const ChannelEncryptRequest = 1303;
	const ChannelEncryptResponse = 1304;
	const ChannelEncryptResult = 1305;
	const BaseBS = 1400;
	const BSPurchaseStart = 1401;
	const BSPurchaseResponse = 1402; // obsolete
	const BSSettleNOVA = 1404; // obsolete
	const BSSettleComplete = 1406;
	const BSBannedRequest = 1407; // obsolete
	const BSInitPayPalTxn = 1408;
	const BSInitPayPalTxnResponse = 1409;
	const BSGetPayPalUserInfo = 1410;
	const BSGetPayPalUserInfoResponse = 1411;
	const BSRefundTxn = 1413; // obsolete
	const BSRefundTxnResponse = 1414; // obsolete
	const BSGetEvents = 1415; // obsolete
	const BSChaseRFRRequest = 1416; // obsolete
	const BSPaymentInstrBan = 1417;
	const BSPaymentInstrBanResponse = 1418;
	const BSProcessGCReports = 1419; // obsolete
	const BSProcessPPReports = 1420; // obsolete
	const BSInitGCBankXferTxn = 1421;
	const BSInitGCBankXferTxnResponse = 1422;
	const BSQueryGCBankXferTxn = 1423; // obsolete
	const BSQueryGCBankXferTxnResponse = 1424; // obsolete
	const BSCommitGCTxn = 1425;
	const BSQueryTransactionStatus = 1426;
	const BSQueryTransactionStatusResponse = 1427;
	const BSQueryCBOrderStatus = 1428; // obsolete
	const BSQueryCBOrderStatusResponse = 1429; // obsolete
	const BSRunRedFlagReport = 1430; // obsolete
	const BSQueryPaymentInstUsage = 1431;
	const BSQueryPaymentInstResponse = 1432;
	const BSQueryTxnExtendedInfo = 1433;
	const BSQueryTxnExtendedInfoResponse = 1434;
	const BSUpdateConversionRates = 1435;
	const BSProcessUSBankReports = 1436; // obsolete
	const BSPurchaseRunFraudChecks = 1437;
	const BSPurchaseRunFraudChecksResponse = 1438;
	const BSStartShippingJobs = 1439; // obsolete
	const BSQueryBankInformation = 1440;
	const BSQueryBankInformationResponse = 1441;
	const BSValidateXsollaSignature = 1445;
	const BSValidateXsollaSignatureResponse = 1446;
	const BSQiwiWalletInvoice = 1448;
	const BSQiwiWalletInvoiceResponse = 1449;
	const BSUpdateInventoryFromProPack = 1450;
	const BSUpdateInventoryFromProPackResponse = 1451;
	const BSSendShippingRequest = 1452;
	const BSSendShippingRequestResponse = 1453;
	const BSGetProPackOrderStatus = 1454;
	const BSGetProPackOrderStatusResponse = 1455;
	const BSCheckJobRunning = 1456;
	const BSCheckJobRunningResponse = 1457;
	const BSResetPackagePurchaseRateLimit = 1458;
	const BSResetPackagePurchaseRateLimitResponse = 1459;
	const BSUpdatePaymentData = 1460;
	const BSUpdatePaymentDataResponse = 1461;
	const BSGetBillingAddress = 1462;
	const BSGetBillingAddressResponse = 1463;
	const BSGetCreditCardInfo = 1464;
	const BSGetCreditCardInfoResponse = 1465;
	const BSRemoveExpiredPaymentData = 1468;
	const BSRemoveExpiredPaymentDataResponse = 1469;
	const BSConvertToCurrentKeys = 1470;
	const BSConvertToCurrentKeysResponse = 1471;
	const BSInitPurchase = 1472;
	const BSInitPurchaseResponse = 1473;
	const BSCompletePurchase = 1474;
	const BSCompletePurchaseResponse = 1475;
	const BSPruneCardUsageStats = 1476;
	const BSPruneCardUsageStatsResponse = 1477;
	const BSStoreBankInformation = 1478;
	const BSStoreBankInformationResponse = 1479;
	const BSVerifyPOSAKey = 1480;
	const BSVerifyPOSAKeyResponse = 1481;
	const BSReverseRedeemPOSAKey = 1482;
	const BSReverseRedeemPOSAKeyResponse = 1483;
	const BSQueryFindCreditCard = 1484;
	const BSQueryFindCreditCardResponse = 1485;
	const BSStatusInquiryPOSAKey = 1486;
	const BSStatusInquiryPOSAKeyResponse = 1487;
	const BSValidateMoPaySignature = 1488;
	const BSValidateMoPaySignatureResponse = 1489;
	const BSMoPayConfirmProductDelivery = 1490;
	const BSMoPayConfirmProductDeliveryResponse = 1491;
	const BSGenerateMoPayMD5 = 1492;
	const BSGenerateMoPayMD5Response = 1493;
	const BSBoaCompraConfirmProductDelivery = 1494;
	const BSBoaCompraConfirmProductDeliveryResponse = 1495;
	const BSGenerateBoaCompraMD5 = 1496;
	const BSGenerateBoaCompraMD5Response = 1497;
	const BSCommitWPTxn = 1498;
	const BaseATS = 1500;
	const ATSStartStressTest = 1501;
	const ATSStopStressTest = 1502;
	const ATSRunFailServerTest = 1503;
	const ATSUFSPerfTestTask = 1504;
	const ATSUFSPerfTestResponse = 1505;
	const ATSCycleTCM = 1506;
	const ATSInitDRMSStressTest = 1507;
	const ATSCallTest = 1508;
	const ATSCallTestReply = 1509;
	const ATSStartExternalStress = 1510;
	const ATSExternalStressJobStart = 1511;
	const ATSExternalStressJobQueued = 1512;
	const ATSExternalStressJobRunning = 1513;
	const ATSExternalStressJobStopped = 1514;
	const ATSExternalStressJobStopAll = 1515;
	const ATSExternalStressActionResult = 1516;
	const ATSStarted = 1517;
	const ATSCSPerfTestTask = 1518;
	const ATSCSPerfTestResponse = 1519;
	const BaseDP = 1600;
	const DPSetPublishingState = 1601;
	const DPGamePlayedStats = 1602; // obsolete
	const DPUniquePlayersStat = 1603;
	const DPStreamingUniquePlayersStat = 1604;
	const DPVacInfractionStats = 1605;
	const DPVacBanStats = 1606;
	const DPBlockingStats = 1607;
	const DPNatTraversalStats = 1608;
	const DPSteamUsageEvent = 1609; // obsolete
	const DPVacCertBanStats = 1610;
	const DPVacCafeBanStats = 1611;
	const DPCloudStats = 1612;
	const DPAchievementStats = 1613;
	const DPAccountCreationStats = 1614;
	const DPGetPlayerCount = 1615;
	const DPGetPlayerCountResponse = 1616;
	const DPGameServersPlayersStats = 1617;
	const DPDownloadRateStatistics = 1618; // obsolete
	const DPFacebookStatistics = 1619;
	const ClientDPCheckSpecialSurvey = 1620;
	const ClientDPCheckSpecialSurveyResponse = 1621;
	const ClientDPSendSpecialSurveyResponse = 1622;
	const ClientDPSendSpecialSurveyResponseReply = 1623;
	const DPStoreSaleStatistics = 1624;
	const ClientDPUpdateAppJobReport = 1625;
	const ClientDPSteam2AppStarted = 1627; // obsolete obsolete
	const DPUpdateContentEvent = 1626;
	const DPPartnerMicroTxns = 1628;
	const DPPartnerMicroTxnsResponse = 1629;
	const ClientDPContentStatsReport = 1630;
	const DPVRUniquePlayersStat = 1631;
	const BaseCM = 1700;
	const CMSetAllowState = 1701;
	const CMSpewAllowState = 1702;
	const CMAppInfoResponseDeprecated = 1703; // obsolete
	const BaseDSS = 1800; // obsolete
	const DSSNewFile = 1801; // obsolete
	const DSSCurrentFileList = 1802; // obsolete
	const DSSSynchList = 1803; // obsolete
	const DSSSynchListResponse = 1804; // obsolete
	const DSSSynchSubscribe = 1805; // obsolete
	const DSSSynchUnsubscribe = 1806; // obsolete
	const BaseEPM = 1900; // obsolete
	const EPMStartProcess = 1901; // obsolete
	const EPMStopProcess = 1902; // obsolete
	const EPMRestartProcess = 1903; // obsolete
	const BaseGC = 2200;
	const GCSendClient = 2200; // obsolete
	const AMRelayToGC = 2201; // obsolete
	const GCUpdatePlayedState = 2202; // obsolete
	const GCCmdRevive = 2203;
	const GCCmdBounce = 2204; // obsolete
	const GCCmdForceBounce = 2205; // obsolete
	const GCCmdDown = 2206;
	const GCCmdDeploy = 2207;
	const GCCmdDeployResponse = 2208;
	const GCCmdSwitch = 2209;
	const AMRefreshSessions = 2210;
	const GCUpdateGSState = 2211; // obsolete
	const GCAchievementAwarded = 2212;
	const GCSystemMessage = 2213;
	const GCValidateSession = 2214; // obsolete
	const GCValidateSessionResponse = 2215; // obsolete
	const GCCmdStatus = 2216;
	const GCRegisterWebInterfaces = 2217; // obsolete
	const GCRegisterWebInterfaces_Deprecated = 2217; // obsolete
	const GCGetAccountDetails = 2218; // obsolete
	const GCGetAccountDetails_DEPRECATED = 2218; // obsolete
	const GCInterAppMessage = 2219;
	const GCGetEmailTemplate = 2220;
	const GCGetEmailTemplateResponse = 2221;
	const ISRelayToGCH = 2222; // obsolete "renamed to GCHRelay"
	const GCHRelay = 2222;
	const GCHRelayClientToIS = 2223; // obsolete "renamed to GCHRelayToClient"
	const GCHRelayToClient = 2223;
	const GCHUpdateSession = 2224;
	const GCHRequestUpdateSession = 2225;
	const GCHRequestStatus = 2226;
	const GCHRequestStatusResponse = 2227;
	const GCHAccountVacStatusChange = 2228;
	const GCHSpawnGC = 2229;
	const GCHSpawnGCResponse = 2230;
	const GCHKillGC = 2231;
	const GCHKillGCResponse = 2232;
	const GCHAccountTradeBanStatusChange = 2233;
	const GCHAccountLockStatusChange = 2234;
	const GCHVacVerificationChange = 2235;
	const GCHAccountPhoneNumberChange = 2236;
	const GCHAccountTwoFactorChange = 2237;
	const BaseP2P = 2500;
	const P2PIntroducerMessage = 2502;
	const BaseSM = 2900;
	const SMExpensiveReport = 2902;
	const SMHourlyReport = 2903;
	const SMFishingReport = 2904;
	const SMPartitionRenames = 2905;
	const SMMonitorSpace = 2906;
	const SMGetSchemaConversionResults = 2907; // obsolete
	const SMGetSchemaConversionResultsResponse = 2908; // obsolete
	const BaseTest = 3000;
	const FailServer = 3000;
	const JobHeartbeatTest = 3001;
	const JobHeartbeatTestResponse = 3002;
	const BaseFTSRange = 3100;
	const FTSGetBrowseCounts = 3101; // obsolete
	const FTSGetBrowseCountsResponse = 3102; // obsolete
	const FTSBrowseClans = 3103; // obsolete
	const FTSBrowseClansResponse = 3104; // obsolete
	const FTSSearchClansByLocation = 3105; // obsolete
	const FTSSearchClansByLocationResponse = 3106; // obsolete
	const FTSSearchPlayersByLocation = 3107; // obsolete
	const FTSSearchPlayersByLocationResponse = 3108; // obsolete
	const FTSClanDeleted = 3109; // obsolete
	const FTSSearch = 3110; // obsolete
	const FTSSearchResponse = 3111; // obsolete
	const FTSSearchStatus = 3112; // obsolete
	const FTSSearchStatusResponse = 3113; // obsolete
	const FTSGetGSPlayStats = 3114; // obsolete
	const FTSGetGSPlayStatsResponse = 3115; // obsolete
	const FTSGetGSPlayStatsForServer = 3116; // obsolete
	const FTSGetGSPlayStatsForServerResponse = 3117; // obsolete
	const FTSReportIPUpdates = 3118; // obsolete
	const BaseCCSRange = 3150;
	const CCSGetComments = 3151; // obsolete
	const CCSGetCommentsResponse = 3152; // obsolete
	const CCSAddComment = 3153; // obsolete
	const CCSAddCommentResponse = 3154; // obsolete
	const CCSDeleteComment = 3155; // obsolete
	const CCSDeleteCommentResponse = 3156; // obsolete
	const CCSPreloadComments = 3157; // obsolete
	const CCSNotifyCommentCount = 3158; // obsolete
	const CCSGetCommentsForNews = 3159; // obsolete
	const CCSGetCommentsForNewsResponse = 3160; // obsolete
	const CCSDeleteAllCommentsByAuthor = 3161;
	const CCSDeleteAllCommentsByAuthorResponse = 3162;
	const BaseLBSRange = 3200;
	const LBSSetScore = 3201;
	const LBSSetScoreResponse = 3202;
	const LBSFindOrCreateLB = 3203;
	const LBSFindOrCreateLBResponse = 3204;
	const LBSGetLBEntries = 3205;
	const LBSGetLBEntriesResponse = 3206;
	const LBSGetLBList = 3207;
	const LBSGetLBListResponse = 3208;
	const LBSSetLBDetails = 3209;
	const LBSDeleteLB = 3210;
	const LBSDeleteLBEntry = 3211;
	const LBSResetLB = 3212;
	const LBSResetLBResponse = 3213;
	const LBSDeleteLBResponse = 3214;
	const BaseOGS = 3400;
	const OGSBeginSession = 3401;
	const OGSBeginSessionResponse = 3402;
	const OGSEndSession = 3403;
	const OGSEndSessionResponse = 3404;
	const OGSWriteAppSessionRow = 3406;
	const BaseBRP = 3600;
	const BRPStartShippingJobs = 3601;
	const BRPProcessUSBankReports = 3602;
	const BRPProcessGCReports = 3603;
	const BRPProcessPPReports = 3604;
	const BRPSettleNOVA = 3605; // obsolete
	const BRPSettleCB = 3606; // obsolete
	const BRPCommitGC = 3607;
	const BRPCommitGCResponse = 3608;
	const BRPFindHungTransactions = 3609;
	const BRPCheckFinanceCloseOutDate = 3610;
	const BRPProcessLicenses = 3611;
	const BRPProcessLicensesResponse = 3612;
	const BRPRemoveExpiredPaymentData = 3613;
	const BRPRemoveExpiredPaymentDataResponse = 3614;
	const BRPConvertToCurrentKeys = 3615;
	const BRPConvertToCurrentKeysResponse = 3616;
	const BRPPruneCardUsageStats = 3617;
	const BRPPruneCardUsageStatsResponse = 3618;
	const BRPCheckActivationCodes = 3619;
	const BRPCheckActivationCodesResponse = 3620;
	const BRPCommitWP = 3621;
	const BRPCommitWPResponse = 3622;
	const BRPProcessWPReports = 3623;
	const BRPProcessPaymentRules = 3624;
	const BRPProcessPartnerPayments = 3625;
	const BRPCheckSettlementReports = 3626;
	const BRPPostTaxToAvalara = 3628;
	const BRPPostTransactionTax = 3629;
	const BRPPostTransactionTaxResponse = 3630;
	const BRPProcessIMReports = 3631;
	const BaseAMRange2 = 4000;
	const AMCreateChat = 4001;
	const AMCreateChatResponse = 4002;
	const AMUpdateChatMetadata = 4003; // obsolete
	const AMPublishChatMetadata = 4004; // obsolete
	const AMSetProfileURL = 4005;
	const AMGetAccountEmailAddress = 4006;
	const AMGetAccountEmailAddressResponse = 4007;
	const AMRequestFriendData = 4008; // obsolete "renamed to AMRequestClanData"
	const AMRequestClanData = 4008;
	const AMRouteToClients = 4009;
	const AMLeaveClan = 4010;
	const AMClanPermissions = 4011;
	const AMClanPermissionsResponse = 4012;
	const AMCreateClanEvent = 4013;
	const AMCreateClanEventResponse = 4014;
	const AMUpdateClanEvent = 4015;
	const AMUpdateClanEventResponse = 4016;
	const AMGetClanEvents = 4017;
	const AMGetClanEventsResponse = 4018;
	const AMDeleteClanEvent = 4019;
	const AMDeleteClanEventResponse = 4020;
	const AMSetClanPermissionSettings = 4021;
	const AMSetClanPermissionSettingsResponse = 4022;
	const AMGetClanPermissionSettings = 4023;
	const AMGetClanPermissionSettingsResponse = 4024;
	const AMPublishChatRoomInfo = 4025;
	const ClientChatRoomInfo = 4026;
	const AMCreateClanAnnouncement = 4027; // obsolete
	const AMCreateClanAnnouncementResponse = 4028; // obsolete
	const AMUpdateClanAnnouncement = 4029; // obsolete
	const AMUpdateClanAnnouncementResponse = 4030; // obsolete
	const AMGetClanAnnouncementsCount = 4031; // obsolete
	const AMGetClanAnnouncementsCountResponse = 4032; // obsolete
	const AMGetClanAnnouncements = 4033; // obsolete
	const AMGetClanAnnouncementsResponse = 4034; // obsolete
	const AMDeleteClanAnnouncement = 4035; // obsolete
	const AMDeleteClanAnnouncementResponse = 4036; // obsolete
	const AMGetSingleClanAnnouncement = 4037; // obsolete
	const AMGetSingleClanAnnouncementResponse = 4038; // obsolete
	const AMGetClanHistory = 4039;
	const AMGetClanHistoryResponse = 4040;
	const AMGetClanPermissionBits = 4041;
	const AMGetClanPermissionBitsResponse = 4042;
	const AMSetClanPermissionBits = 4043;
	const AMSetClanPermissionBitsResponse = 4044;
	const AMSessionInfoRequest = 4045;
	const AMSessionInfoResponse = 4046;
	const AMValidateWGToken = 4047;
	const AMGetSingleClanEvent = 4048;
	const AMGetSingleClanEventResponse = 4049;
	const AMGetClanRank = 4050;
	const AMGetClanRankResponse = 4051;
	const AMSetClanRank = 4052;
	const AMSetClanRankResponse = 4053;
	const AMGetClanPOTW = 4054;
	const AMGetClanPOTWResponse = 4055;
	const AMSetClanPOTW = 4056;
	const AMSetClanPOTWResponse = 4057;
	const AMRequestChatMetadata = 4058; // obsolete
	const AMDumpUser = 4059;
	const AMKickUserFromClan = 4060;
	const AMAddFounderToClan = 4061;
	const AMValidateWGTokenResponse = 4062;
	const AMSetCommunityState = 4063;
	const AMSetAccountDetails = 4064;
	const AMGetChatBanList = 4065;
	const AMGetChatBanListResponse = 4066;
	const AMUnBanFromChat = 4067;
	const AMSetClanDetails = 4068;
	const AMGetAccountLinks = 4069;
	const AMGetAccountLinksResponse = 4070;
	const AMSetAccountLinks = 4071;
	const AMSetAccountLinksResponse = 4072;
	const AMGetUserGameStats = 4073;
	const AMGetUserGameStatsResponse = 4074;
	const AMCheckClanMembership = 4075;
	const AMGetClanMembers = 4076;
	const AMGetClanMembersResponse = 4077;
	const AMJoinPublicClan = 4078;
	const AMNotifyChatOfClanChange = 4079;
	const AMResubmitPurchase = 4080;
	const AMAddFriend = 4081;
	const AMAddFriendResponse = 4082;
	const AMRemoveFriend = 4083;
	const AMDumpClan = 4084;
	const AMChangeClanOwner = 4085;
	const AMCancelEasyCollect = 4086;
	const AMCancelEasyCollectResponse = 4087;
	const AMGetClanMembershipList = 4088; // obsolete
	const AMGetClanMembershipListResponse = 4089; // obsolete
	const AMClansInCommon = 4090;
	const AMClansInCommonResponse = 4091;
	const AMIsValidAccountID = 4092;
	const AMConvertClan = 4093;
	const AMGetGiftTargetListRelay = 4094; // obsolete
	const AMWipeFriendsList = 4095;
	const AMSetIgnored = 4096;
	const AMClansInCommonCountResponse = 4097;
	const AMFriendsList = 4098;
	const AMFriendsListResponse = 4099;
	const AMFriendsInCommon = 4100;
	const AMFriendsInCommonResponse = 4101;
	const AMFriendsInCommonCountResponse = 4102;
	const AMClansInCommonCount = 4103;
	const AMChallengeVerdict = 4104;
	const AMChallengeNotification = 4105;
	const AMFindGSByIP = 4106;
	const AMFoundGSByIP = 4107;
	const AMGiftRevoked = 4108;
	const AMCreateAccountRecord = 4109;
	const AMUserClanList = 4110;
	const AMUserClanListResponse = 4111;
	const AMGetAccountDetails2 = 4112;
	const AMGetAccountDetailsResponse2 = 4113;
	const AMSetCommunityProfileSettings = 4114;
	const AMSetCommunityProfileSettingsResponse = 4115;
	const AMGetCommunityPrivacyState = 4116;
	const AMGetCommunityPrivacyStateResponse = 4117;
	const AMCheckClanInviteRateLimiting = 4118;
	const AMGetUserAchievementStatus = 4119;
	const AMGetIgnored = 4120;
	const AMGetIgnoredResponse = 4121;
	const AMSetIgnoredResponse = 4122;
	const AMSetFriendRelationshipNone = 4123;
	const AMGetFriendRelationship = 4124;
	const AMGetFriendRelationshipResponse = 4125;
	const AMServiceModulesCache = 4126;
	const AMServiceModulesCall = 4127;
	const AMServiceModulesCallResponse = 4128;
	const AMGetCaptchaDataForIP = 4129;
	const AMGetCaptchaDataForIPResponse = 4130;
	const AMValidateCaptchaDataForIP = 4131;
	const AMValidateCaptchaDataForIPResponse = 4132;
	const AMTrackFailedAuthByIP = 4133;
	const AMGetCaptchaDataByGID = 4134;
	const AMGetCaptchaDataByGIDResponse = 4135;
	const AMGetLobbyList = 4136; // obsolete
	const AMGetLobbyListResponse = 4137; // obsolete
	const AMGetLobbyMetadata = 4138; // obsolete
	const AMGetLobbyMetadataResponse = 4139; // obsolete
	const CommunityAddFriendNews = 4140;
	const AMAddClanNews = 4141; // obsolete
	const AMWriteNews = 4142; // obsolete
	const AMFindClanUser = 4143;
	const AMFindClanUserResponse = 4144;
	const AMBanFromChat = 4145;
	const AMGetUserHistoryResponse = 4146; // obsolete
	const AMGetUserNewsSubscriptions = 4147;
	const AMGetUserNewsSubscriptionsResponse = 4148;
	const AMSetUserNewsSubscriptions = 4149;
	const AMGetUserNews = 4150; // obsolete
	const AMGetUserNewsResponse = 4151; // obsolete
	const AMSendQueuedEmails = 4152;
	const AMSetLicenseFlags = 4153;
	const AMGetUserHistory = 4154; // obsolete
	const CommunityDeleteUserNews = 4155;
	const AMAllowUserFilesRequest = 4156;
	const AMAllowUserFilesResponse = 4157;
	const AMGetAccountStatus = 4158;
	const AMGetAccountStatusResponse = 4159;
	const AMEditBanReason = 4160;
	const AMCheckClanMembershipResponse = 4161;
	const AMProbeClanMembershipList = 4162;
	const AMProbeClanMembershipListResponse = 4163;
	const AMGetFriendsLobbies = 4165;
	const AMGetFriendsLobbiesResponse = 4166;
	const AMGetUserFriendNewsResponse = 4172;
	const CommunityGetUserFriendNews = 4173;
	const AMGetUserClansNewsResponse = 4174;
	const AMGetUserClansNews = 4175;
	const AMStoreInitPurchase = 4176; // obsolete
	const AMStoreInitPurchaseResponse = 4177; // obsolete
	const AMStoreGetFinalPrice = 4178; // obsolete
	const AMStoreGetFinalPriceResponse = 4179; // obsolete
	const AMStoreCompletePurchase = 4180; // obsolete
	const AMStoreCancelPurchase = 4181; // obsolete
	const AMStorePurchaseResponse = 4182; // obsolete
	const AMCreateAccountRecordInSteam3 = 4183; // obsolete
	const AMGetPreviousCBAccount = 4184;
	const AMGetPreviousCBAccountResponse = 4185;
	const AMUpdateBillingAddress = 4186; // obsolete
	const AMUpdateBillingAddressResponse = 4187; // obsolete
	const AMGetBillingAddress = 4188; // obsolete
	const AMGetBillingAddressResponse = 4189; // obsolete
	const AMGetUserLicenseHistory = 4190;
	const AMGetUserLicenseHistoryResponse = 4191;
	const AMSupportChangePassword = 4194;
	const AMSupportChangeEmail = 4195;
	const AMSupportChangeSecretQA = 4196; // obsolete
	const AMResetUserVerificationGSByIP = 4197;
	const AMUpdateGSPlayStats = 4198;
	const AMSupportEnableOrDisable = 4199;
	const AMGetComments = 4200; // obsolete
	const AMGetCommentsResponse = 4201; // obsolete
	const AMAddComment = 4202; // obsolete
	const AMAddCommentResponse = 4203; // obsolete
	const AMDeleteComment = 4204; // obsolete
	const AMDeleteCommentResponse = 4205; // obsolete
	const AMGetPurchaseStatus = 4206;
	const AMSupportIsAccountEnabled = 4209;
	const AMSupportIsAccountEnabledResponse = 4210;
	const AMGetUserStats = 4211;
	const AMSupportKickSession = 4212;
	const AMGSSearch = 4213;
	const MarketingMessageUpdate = 4216;
	const AMRouteFriendMsg = 4219;
	const AMTicketAuthRequestOrResponse = 4220;
	const AMVerifyDepotManagementRights = 4222;
	const AMVerifyDepotManagementRightsResponse = 4223;
	const AMAddFreeLicense = 4224;
	const AMGetUserFriendsMinutesPlayed = 4225; // obsolete
	const AMGetUserFriendsMinutesPlayedResponse = 4226; // obsolete
	const AMGetUserMinutesPlayed = 4227; // obsolete
	const AMGetUserMinutesPlayedResponse = 4228; // obsolete
	const AMValidateEmailLink = 4231;
	const AMValidateEmailLinkResponse = 4232;
	const AMAddUsersToMarketingTreatment = 4234; // obsolete
	const AMStoreUserStats = 4236;
	const AMGetUserGameplayInfo = 4237; // obsolete
	const AMGetUserGameplayInfoResponse = 4238; // obsolete
	const AMGetCardList = 4239; // obsolete
	const AMGetCardListResponse = 4240; // obsolete
	const AMDeleteStoredCard = 4241;
	const AMRevokeLegacyGameKeys = 4242;
	const AMGetWalletDetails = 4244;
	const AMGetWalletDetailsResponse = 4245;
	const AMDeleteStoredPaymentInfo = 4246;
	const AMGetStoredPaymentSummary = 4247;
	const AMGetStoredPaymentSummaryResponse = 4248;
	const AMGetWalletConversionRate = 4249;
	const AMGetWalletConversionRateResponse = 4250;
	const AMConvertWallet = 4251;
	const AMConvertWalletResponse = 4252;
	const AMRelayGetFriendsWhoPlayGame = 4253; // obsolete
	const AMRelayGetFriendsWhoPlayGameResponse = 4254; // obsolete
	const AMSetPreApproval = 4255;
	const AMSetPreApprovalResponse = 4256;
	const AMMarketingTreatmentUpdate = 4257; // obsolete
	const AMCreateRefund = 4258;
	const AMCreateRefundResponse = 4259;
	const AMCreateChargeback = 4260;
	const AMCreateChargebackResponse = 4261;
	const AMCreateDispute = 4262;
	const AMCreateDisputeResponse = 4263;
	const AMClearDispute = 4264;
	const AMClearDisputeResponse = 4265;
	const AMPlayerNicknameList = 4266;
	const AMPlayerNicknameListResponse = 4267;
	const AMSetDRMTestConfig = 4268;
	const AMGetUserCurrentGameInfo = 4269;
	const AMGetUserCurrentGameInfoResponse = 4270;
	const AMGetGSPlayerList = 4271;
	const AMGetGSPlayerListResponse = 4272;
	const AMUpdatePersonaStateCache = 4275; // obsolete
	const AMGetGameMembers = 4276;
	const AMGetGameMembersResponse = 4277;
	const AMGetSteamIDForMicroTxn = 4278;
	const AMGetSteamIDForMicroTxnResponse = 4279;
	const AMAddPublisherUser = 4280;
	const AMRemovePublisherUser = 4281;
	const AMGetUserLicenseList = 4282;
	const AMGetUserLicenseListResponse = 4283;
	const AMReloadGameGroupPolicy = 4284;
	const AMAddFreeLicenseResponse = 4285;
	const AMVACStatusUpdate = 4286;
	const AMGetAccountDetails = 4287;
	const AMGetAccountDetailsResponse = 4288;
	const AMGetPlayerLinkDetails = 4289;
	const AMGetPlayerLinkDetailsResponse = 4290;
	const AMSubscribeToPersonaFeed = 4291; // obsolete
	const AMGetUserVacBanList = 4292; // obsolete
	const AMGetUserVacBanListResponse = 4293; // obsolete
	const AMGetAccountFlagsForWGSpoofing = 4294;
	const AMGetAccountFlagsForWGSpoofingResponse = 4295;
	const AMGetFriendsWishlistInfo = 4296; // obsolete
	const AMGetFriendsWishlistInfoResponse = 4297; // obsolete
	const AMGetClanOfficers = 4298;
	const AMGetClanOfficersResponse = 4299;
	const AMNameChange = 4300;
	const AMGetNameHistory = 4301;
	const AMGetNameHistoryResponse = 4302;
	const AMUpdateProviderStatus = 4305;
	const AMClearPersonaMetadataBlob = 4306; // obsolete
	const AMSupportRemoveAccountSecurity = 4307;
	const AMIsAccountInCaptchaGracePeriod = 4308;
	const AMIsAccountInCaptchaGracePeriodResponse = 4309;
	const AMAccountPS3Unlink = 4310;
	const AMAccountPS3UnlinkResponse = 4311;
	const AMStoreUserStatsResponse = 4312;
	const AMGetAccountPSNInfo = 4313;
	const AMGetAccountPSNInfoResponse = 4314;
	const AMAuthenticatedPlayerList = 4315;
	const AMGetUserGifts = 4316;
	const AMGetUserGiftsResponse = 4317;
	const AMTransferLockedGifts = 4320;
	const AMTransferLockedGiftsResponse = 4321;
	const AMPlayerHostedOnGameServer = 4322;
	const AMGetAccountBanInfo = 4323;
	const AMGetAccountBanInfoResponse = 4324;
	const AMRecordBanEnforcement = 4325;
	const AMRollbackGiftTransfer = 4326;
	const AMRollbackGiftTransferResponse = 4327;
	const AMHandlePendingTransaction = 4328;
	const AMRequestClanDetails = 4329;
	const AMDeleteStoredPaypalAgreement = 4330;
	const AMGameServerUpdate = 4331;
	const AMGameServerRemove = 4332;
	const AMGetPaypalAgreements = 4333;
	const AMGetPaypalAgreementsResponse = 4334;
	const AMGameServerPlayerCompatibilityCheck = 4335;
	const AMGameServerPlayerCompatibilityCheckResponse = 4336;
	const AMRenewLicense = 4337;
	const AMGetAccountCommunityBanInfo = 4338;
	const AMGetAccountCommunityBanInfoResponse = 4339;
	const AMGameServerAccountChangePassword = 4340;
	const AMGameServerAccountDeleteAccount = 4341;
	const AMRenewAgreement = 4342;
	const AMSendEmail = 4343; // obsolete
	const AMXsollaPayment = 4344;
	const AMXsollaPaymentResponse = 4345;
	const AMAcctAllowedToPurchase = 4346;
	const AMAcctAllowedToPurchaseResponse = 4347;
	const AMSwapKioskDeposit = 4348;
	const AMSwapKioskDepositResponse = 4349;
	const AMSetUserGiftUnowned = 4350;
	const AMSetUserGiftUnownedResponse = 4351;
	const AMClaimUnownedUserGift = 4352;
	const AMClaimUnownedUserGiftResponse = 4353;
	const AMSetClanName = 4354;
	const AMSetClanNameResponse = 4355;
	const AMGrantCoupon = 4356;
	const AMGrantCouponResponse = 4357;
	const AMIsPackageRestrictedInUserCountry = 4358;
	const AMIsPackageRestrictedInUserCountryResponse = 4359;
	const AMHandlePendingTransactionResponse = 4360;
	const AMGrantGuestPasses2 = 4361;
	const AMGrantGuestPasses2Response = 4362;
	const AMSessionQuery = 4363;
	const AMSessionQueryResponse = 4364;
	const AMGetPlayerBanDetails = 4365;
	const AMGetPlayerBanDetailsResponse = 4366;
	const AMFinalizePurchase = 4367;
	const AMFinalizePurchaseResponse = 4368;
	const AMPersonaChangeResponse = 4372;
	const AMGetClanDetailsForForumCreation = 4373;
	const AMGetClanDetailsForForumCreationResponse = 4374;
	const AMGetPendingNotificationCount = 4375;
	const AMGetPendingNotificationCountResponse = 4376;
	const AMPasswordHashUpgrade = 4377;
	const AMMoPayPayment = 4378;
	const AMMoPayPaymentResponse = 4379;
	const AMBoaCompraPayment = 4380;
	const AMBoaCompraPaymentResponse = 4381;
	const AMExpireCaptchaByGID = 4382;
	const AMCompleteExternalPurchase = 4383;
	const AMCompleteExternalPurchaseResponse = 4384;
	const AMResolveNegativeWalletCredits = 4385;
	const AMResolveNegativeWalletCreditsResponse = 4386;
	const AMPayelpPayment = 4387;
	const AMPayelpPaymentResponse = 4388;
	const AMPlayerGetClanBasicDetails = 4389;
	const AMPlayerGetClanBasicDetailsResponse = 4390;
	const AMMOLPayment = 4391;
	const AMMOLPaymentResponse = 4392;
	const GetUserIPCountry = 4393;
	const GetUserIPCountryResponse = 4394;
	const NotificationOfSuspiciousActivity = 4395;
	const AMDegicaPayment = 4396;
	const AMDegicaPaymentResponse = 4397;
	const AMEClubPayment = 4398;
	const AMEClubPaymentResponse = 4399;
	const AMPayPalPaymentsHubPayment = 4400;
	const AMPayPalPaymentsHubPaymentResponse = 4401;
	const AMTwoFactorRecoverAuthenticatorRequest = 4402;
	const AMTwoFactorRecoverAuthenticatorResponse = 4403;
	const AMSmart2PayPayment = 4404;
	const AMSmart2PayPaymentResponse = 4405;
	const AMValidatePasswordResetCodeAndSendSmsRequest = 4406;
	const AMValidatePasswordResetCodeAndSendSmsResponse = 4407;
	const AMGetAccountResetDetailsRequest = 4408;
	const AMGetAccountResetDetailsResponse = 4409;
	const AMBitPayPayment = 4410;
	const AMBitPayPaymentResponse = 4411;
	const AMSendAccountInfoUpdate = 4412;
	const BasePSRange = 5000;
	const PSCreateShoppingCart = 5001;
	const PSCreateShoppingCartResponse = 5002;
	const PSIsValidShoppingCart = 5003;
	const PSIsValidShoppingCartResponse = 5004;
	const PSAddPackageToShoppingCart = 5005;
	const PSAddPackageToShoppingCartResponse = 5006;
	const PSRemoveLineItemFromShoppingCart = 5007;
	const PSRemoveLineItemFromShoppingCartResponse = 5008;
	const PSGetShoppingCartContents = 5009;
	const PSGetShoppingCartContentsResponse = 5010;
	const PSAddWalletCreditToShoppingCart = 5011;
	const PSAddWalletCreditToShoppingCartResponse = 5012;
	const BaseUFSRange = 5200;
	const ClientUFSUploadFileRequest = 5202;
	const ClientUFSUploadFileResponse = 5203;
	const ClientUFSUploadFileChunk = 5204;
	const ClientUFSUploadFileFinished = 5205;
	const ClientUFSGetFileListForApp = 5206;
	const ClientUFSGetFileListForAppResponse = 5207;
	const ClientUFSDownloadRequest = 5210;
	const ClientUFSDownloadResponse = 5211;
	const ClientUFSDownloadChunk = 5212;
	const ClientUFSLoginRequest = 5213;
	const ClientUFSLoginResponse = 5214;
	const UFSReloadPartitionInfo = 5215;
	const ClientUFSTransferHeartbeat = 5216;
	const UFSSynchronizeFile = 5217;
	const UFSSynchronizeFileResponse = 5218;
	const ClientUFSDeleteFileRequest = 5219;
	const ClientUFSDeleteFileResponse = 5220;
	const UFSDownloadRequest = 5221; // obsolete
	const UFSDownloadResponse = 5222; // obsolete
	const UFSDownloadChunk = 5223; // obsolete
	const ClientUFSGetUGCDetails = 5226;
	const ClientUFSGetUGCDetailsResponse = 5227;
	const UFSUpdateFileFlags = 5228;
	const UFSUpdateFileFlagsResponse = 5229;
	const ClientUFSGetSingleFileInfo = 5230;
	const ClientUFSGetSingleFileInfoResponse = 5231;
	const ClientUFSShareFile = 5232;
	const ClientUFSShareFileResponse = 5233;
	const UFSReloadAccount = 5234;
	const UFSReloadAccountResponse = 5235;
	const UFSUpdateRecordBatched = 5236;
	const UFSUpdateRecordBatchedResponse = 5237;
	const UFSMigrateFile = 5238;
	const UFSMigrateFileResponse = 5239;
	const UFSGetUGCURLs = 5240;
	const UFSGetUGCURLsResponse = 5241;
	const UFSHttpUploadFileFinishRequest = 5242;
	const UFSHttpUploadFileFinishResponse = 5243;
	const UFSDownloadStartRequest = 5244;
	const UFSDownloadStartResponse = 5245;
	const UFSDownloadChunkRequest = 5246;
	const UFSDownloadChunkResponse = 5247;
	const UFSDownloadFinishRequest = 5248;
	const UFSDownloadFinishResponse = 5249;
	const UFSFlushURLCache = 5250;
	const UFSUploadCommit = 5251;
	const UFSUploadCommitResponse = 5252;
	const UFSMigrateFileAppID = 5253;
	const UFSMigrateFileAppIDResponse = 5254;
	const BaseClient2 = 5400;
	const ClientRequestForgottenPasswordEmail = 5401;
	const ClientRequestForgottenPasswordEmailResponse = 5402;
	const ClientCreateAccountResponse = 5403;
	const ClientResetForgottenPassword = 5404;
	const ClientResetForgottenPasswordResponse = 5405;
	const ClientCreateAccount2 = 5406;
	const ClientInformOfResetForgottenPassword = 5407;
	const ClientInformOfResetForgottenPasswordResponse = 5408;
	const ClientAnonUserLogOn_Deprecated = 5409; // obsolete
	const ClientGamesPlayedWithDataBlob = 5410;
	const ClientUpdateUserGameInfo = 5411;
	const ClientFileToDownload = 5412;
	const ClientFileToDownloadResponse = 5413;
	const ClientLBSSetScore = 5414;
	const ClientLBSSetScoreResponse = 5415;
	const ClientLBSFindOrCreateLB = 5416;
	const ClientLBSFindOrCreateLBResponse = 5417;
	const ClientLBSGetLBEntries = 5418;
	const ClientLBSGetLBEntriesResponse = 5419;
	const ClientMarketingMessageUpdate = 5420; // obsolete
	const ClientChatDeclined = 5426;
	const ClientFriendMsgIncoming = 5427;
	const ClientAuthList_Deprecated = 5428; // obsolete
	const ClientTicketAuthComplete = 5429;
	const ClientIsLimitedAccount = 5430;
	const ClientRequestAuthList = 5431;
	const ClientAuthList = 5432;
	const ClientStat = 5433;
	const ClientP2PConnectionInfo = 5434;
	const ClientP2PConnectionFailInfo = 5435;
	const ClientGetNumberOfCurrentPlayers = 5436; // obsolete
	const ClientGetNumberOfCurrentPlayersResponse = 5437; // obsolete
	const ClientGetDepotDecryptionKey = 5438;
	const ClientGetDepotDecryptionKeyResponse = 5439;
	const GSPerformHardwareSurvey = 5440;
	const ClientGetAppBetaPasswords = 5441;
	const ClientGetAppBetaPasswordsResponse = 5442;
	const ClientEnableTestLicense = 5443;
	const ClientEnableTestLicenseResponse = 5444;
	const ClientDisableTestLicense = 5445;
	const ClientDisableTestLicenseResponse = 5446;
	const ClientRequestValidationMail = 5448;
	const ClientRequestValidationMailResponse = 5449;
	const ClientCheckAppBetaPassword = 5450;
	const ClientCheckAppBetaPasswordResponse = 5451;
	const ClientToGC = 5452;
	const ClientFromGC = 5453;
	const ClientRequestChangeMail = 5454;
	const ClientRequestChangeMailResponse = 5455;
	const ClientEmailAddrInfo = 5456;
	const ClientPasswordChange3 = 5457;
	const ClientEmailChange3 = 5458;
	const ClientPersonalQAChange3 = 5459;
	const ClientResetForgottenPassword3 = 5460;
	const ClientRequestForgottenPasswordEmail3 = 5461;
	const ClientCreateAccount3 = 5462; // obsolete
	const ClientNewLoginKey = 5463;
	const ClientNewLoginKeyAccepted = 5464;
	const ClientLogOnWithHash_Deprecated = 5465; // obsolete
	const ClientStoreUserStats2 = 5466;
	const ClientStatsUpdated = 5467;
	const ClientActivateOEMLicense = 5468;
	const ClientRegisterOEMMachine = 5469;
	const ClientRegisterOEMMachineResponse = 5470;
	const ClientRequestedClientStats = 5480;
	const ClientStat2Int32 = 5481;
	const ClientStat2 = 5482;
	const ClientVerifyPassword = 5483;
	const ClientVerifyPasswordResponse = 5484;
	const ClientDRMDownloadRequest = 5485;
	const ClientDRMDownloadResponse = 5486;
	const ClientDRMFinalResult = 5487;
	const ClientGetFriendsWhoPlayGame = 5488;
	const ClientGetFriendsWhoPlayGameResponse = 5489;
	const ClientOGSBeginSession = 5490;
	const ClientOGSBeginSessionResponse = 5491;
	const ClientOGSEndSession = 5492;
	const ClientOGSEndSessionResponse = 5493;
	const ClientOGSWriteRow = 5494;
	const ClientDRMTest = 5495;
	const ClientDRMTestResult = 5496;
	const ClientServerUnavailable = 5500;
	const ClientServersAvailable = 5501;
	const ClientRegisterAuthTicketWithCM = 5502;
	const ClientGCMsgFailed = 5503;
	const ClientMicroTxnAuthRequest = 5504;
	const ClientMicroTxnAuthorize = 5505;
	const ClientMicroTxnAuthorizeResponse = 5506;
	const ClientAppMinutesPlayedData = 5507;
	const ClientGetMicroTxnInfo = 5508;
	const ClientGetMicroTxnInfoResponse = 5509;
	const ClientMarketingMessageUpdate2 = 5510;
	const ClientDeregisterWithServer = 5511;
	const ClientSubscribeToPersonaFeed = 5512;
	const ClientLogon = 5514;
	const ClientGetClientDetails = 5515;
	const ClientGetClientDetailsResponse = 5516;
	const ClientReportOverlayDetourFailure = 5517;
	const ClientGetClientAppList = 5518;
	const ClientGetClientAppListResponse = 5519;
	const ClientInstallClientApp = 5520;
	const ClientInstallClientAppResponse = 5521;
	const ClientUninstallClientApp = 5522;
	const ClientUninstallClientAppResponse = 5523;
	const ClientSetClientAppUpdateState = 5524;
	const ClientSetClientAppUpdateStateResponse = 5525;
	const ClientRequestEncryptedAppTicket = 5526;
	const ClientRequestEncryptedAppTicketResponse = 5527;
	const ClientWalletInfoUpdate = 5528;
	const ClientLBSSetUGC = 5529;
	const ClientLBSSetUGCResponse = 5530;
	const ClientAMGetClanOfficers = 5531;
	const ClientAMGetClanOfficersResponse = 5532;
	const ClientCheckFileSignature = 5533;
	const ClientCheckFileSignatureResponse = 5534;
	const ClientFriendProfileInfo = 5535;
	const ClientFriendProfileInfoResponse = 5536;
	const ClientUpdateMachineAuth = 5537;
	const ClientUpdateMachineAuthResponse = 5538;
	const ClientReadMachineAuth = 5539;
	const ClientReadMachineAuthResponse = 5540;
	const ClientRequestMachineAuth = 5541;
	const ClientRequestMachineAuthResponse = 5542;
	const ClientScreenshotsChanged = 5543;
	const ClientEmailChange4 = 5544;
	const ClientEmailChangeResponse4 = 5545;
	const ClientGetCDNAuthToken = 5546;
	const ClientGetCDNAuthTokenResponse = 5547;
	const ClientDownloadRateStatistics = 5548;
	const ClientRequestAccountData = 5549;
	const ClientRequestAccountDataResponse = 5550;
	const ClientResetForgottenPassword4 = 5551;
	const ClientHideFriend = 5552;
	const ClientFriendsGroupsList = 5553;
	const ClientGetClanActivityCounts = 5554;
	const ClientGetClanActivityCountsResponse = 5555;
	const ClientOGSReportString = 5556;
	const ClientOGSReportBug = 5557;
	const ClientSentLogs = 5558;
	const ClientLogonGameServer = 5559;
	const AMClientCreateFriendsGroup = 5560;
	const AMClientCreateFriendsGroupResponse = 5561;
	const AMClientDeleteFriendsGroup = 5562;
	const AMClientDeleteFriendsGroupResponse = 5563;
	const AMClientRenameFriendsGroup = 5564;
	const AMClientRenameFriendsGroupResponse = 5565;
	const AMClientAddFriendToGroup = 5566;
	const AMClientAddFriendToGroupResponse = 5567;
	const AMClientRemoveFriendFromGroup = 5568;
	const AMClientRemoveFriendFromGroupResponse = 5569;
	const ClientAMGetPersonaNameHistory = 5570;
	const ClientAMGetPersonaNameHistoryResponse = 5571;
	const ClientRequestFreeLicense = 5572;
	const ClientRequestFreeLicenseResponse = 5573;
	const ClientDRMDownloadRequestWithCrashData = 5574;
	const ClientAuthListAck = 5575;
	const ClientItemAnnouncements = 5576;
	const ClientRequestItemAnnouncements = 5577;
	const ClientFriendMsgEchoToSender = 5578;
	const ClientChangeSteamGuardOptions = 5579; // obsolete
	const ClientChangeSteamGuardOptionsResponse = 5580; // obsolete
	const ClientOGSGameServerPingSample = 5581;
	const ClientCommentNotifications = 5582;
	const ClientRequestCommentNotifications = 5583;
	const ClientPersonaChangeResponse = 5584;
	const ClientRequestWebAPIAuthenticateUserNonce = 5585;
	const ClientRequestWebAPIAuthenticateUserNonceResponse = 5586;
	const ClientPlayerNicknameList = 5587;
	const AMClientSetPlayerNickname = 5588;
	const AMClientSetPlayerNicknameResponse = 5589;
	const ClientRequestOAuthTokenForApp = 5590; // obsolete
	const ClientRequestOAuthTokenForAppResponse = 5591; // obsolete
	const ClientCreateAccountProto = 5590;
	const ClientCreateAccountProtoResponse = 5591;
	const ClientGetNumberOfCurrentPlayersDP = 5592;
	const ClientGetNumberOfCurrentPlayersDPResponse = 5593;
	const ClientServiceMethod = 5594;
	const ClientServiceMethodResponse = 5595;
	const ClientFriendUserStatusPublished = 5596;
	const ClientCurrentUIMode = 5597;
	const ClientVanityURLChangedNotification = 5598;
	const ClientUserNotifications = 5599;
	const BaseDFS = 5600;
	const DFSGetFile = 5601;
	const DFSInstallLocalFile = 5602;
	const DFSConnection = 5603;
	const DFSConnectionReply = 5604;
	const ClientDFSAuthenticateRequest = 5605;
	const ClientDFSAuthenticateResponse = 5606;
	const ClientDFSEndSession = 5607;
	const DFSPurgeFile = 5608;
	const DFSRouteFile = 5609;
	const DFSGetFileFromServer = 5610;
	const DFSAcceptedResponse = 5611;
	const DFSRequestPingback = 5612;
	const DFSRecvTransmitFile = 5613;
	const DFSSendTransmitFile = 5614;
	const DFSRequestPingback2 = 5615;
	const DFSResponsePingback2 = 5616;
	const ClientDFSDownloadStatus = 5617;
	const DFSStartTransfer = 5618;
	const DFSTransferComplete = 5619;
	const DFSRouteFileResponse = 5620;
	const BaseMDS = 5800;
	const ClientMDSLoginRequest = 5801; // obsolete
	const ClientMDSLoginResponse = 5802; // obsolete
	const ClientMDSUploadManifestRequest = 5803; // obsolete
	const ClientMDSUploadManifestResponse = 5804; // obsolete
	const ClientMDSTransmitManifestDataChunk = 5805; // obsolete
	const ClientMDSHeartbeat = 5806; // obsolete
	const ClientMDSUploadDepotChunks = 5807; // obsolete
	const ClientMDSUploadDepotChunksResponse = 5808; // obsolete
	const ClientMDSInitDepotBuildRequest = 5809; // obsolete
	const ClientMDSInitDepotBuildResponse = 5810; // obsolete
	const AMToMDSGetDepotDecryptionKey = 5812;
	const MDSToAMGetDepotDecryptionKeyResponse = 5813;
	const MDSGetVersionsForDepot = 5814; // obsolete
	const MDSGetVersionsForDepotResponse = 5815; // obsolete
	const MDSSetPublicVersionForDepot = 5816; // obsolete
	const MDSSetPublicVersionForDepotResponse = 5817; // obsolete
	const ClientMDSInitWorkshopBuildRequest = 5816; // obsolete
	const ClientMDSInitWorkshopBuildResponse = 5817; // obsolete
	const ClientMDSGetDepotManifest = 5818; // obsolete
	const ClientMDSGetDepotManifestResponse = 5819; // obsolete
	const ClientMDSGetDepotManifestChunk = 5820; // obsolete
	const ClientMDSUploadRateTest = 5823; // obsolete
	const ClientMDSUploadRateTestResponse = 5824; // obsolete
	const MDSDownloadDepotChunksAck = 5825; // obsolete
	const MDSContentServerStatsBroadcast = 5826; // obsolete
	const MDSContentServerConfigRequest = 5827;
	const MDSContentServerConfig = 5828;
	const MDSGetDepotManifest = 5829;
	const MDSGetDepotManifestResponse = 5830;
	const MDSGetDepotManifestChunk = 5831;
	const MDSGetDepotChunk = 5832;
	const MDSGetDepotChunkResponse = 5833;
	const MDSGetDepotChunkChunk = 5834;
	const MDSUpdateContentServerConfig = 5835; // obsolete
	const MDSGetServerListForUser = 5836;
	const MDSGetServerListForUserResponse = 5837;
	const ClientMDSRegisterAppBuild = 5838; // obsolete
	const ClientMDSRegisterAppBuildResponse = 5839; // obsolete
	const ClientMDSSetAppBuildLive = 5840; // obsolete
	const ClientMDSSetAppBuildLiveResponse = 5841; // obsolete
	const ClientMDSGetPrevDepotBuild = 5842; // obsolete
	const ClientMDSGetPrevDepotBuildResponse = 5843; // obsolete
	const MDSToCSFlushChunk = 5844;
	const ClientMDSSignInstallScript = 5845; // obsolete
	const ClientMDSSignInstallScriptResponse = 5846; // obsolete
	const MDSMigrateChunk = 5847;
	const MDSMigrateChunkResponse = 5848;
	const CSBase = 6200;
	const CSPing = 6201;
	const CSPingResponse = 6202;
	const GMSBase = 6400;
	const GMSGameServerReplicate = 6401;
	const ClientGMSServerQuery = 6403;
	const GMSClientServerQueryResponse = 6404;
	const AMGMSGameServerUpdate = 6405;
	const AMGMSGameServerRemove = 6406;
	const GameServerOutOfDate = 6407;
	const DeviceAuthorizationBase = 6500;
	const ClientAuthorizeLocalDeviceRequest = 6501;
	const ClientAuthorizeLocalDevice = 6502;
	const ClientDeauthorizeDeviceRequest = 6503;
	const ClientDeauthorizeDevice = 6504;
	const ClientUseLocalDeviceAuthorizations = 6505;
	const ClientGetAuthorizedDevices = 6506;
	const ClientGetAuthorizedDevicesResponse = 6507;
	const AMNotifySessionDeviceAuthorized = 6508;
	const MMSBase = 6600;
	const ClientMMSCreateLobby = 6601;
	const ClientMMSCreateLobbyResponse = 6602;
	const ClientMMSJoinLobby = 6603;
	const ClientMMSJoinLobbyResponse = 6604;
	const ClientMMSLeaveLobby = 6605;
	const ClientMMSLeaveLobbyResponse = 6606;
	const ClientMMSGetLobbyList = 6607;
	const ClientMMSGetLobbyListResponse = 6608;
	const ClientMMSSetLobbyData = 6609;
	const ClientMMSSetLobbyDataResponse = 6610;
	const ClientMMSGetLobbyData = 6611;
	const ClientMMSLobbyData = 6612;
	const ClientMMSSendLobbyChatMsg = 6613;
	const ClientMMSLobbyChatMsg = 6614;
	const ClientMMSSetLobbyOwner = 6615;
	const ClientMMSSetLobbyOwnerResponse = 6616;
	const ClientMMSSetLobbyGameServer = 6617;
	const ClientMMSLobbyGameServerSet = 6618;
	const ClientMMSUserJoinedLobby = 6619;
	const ClientMMSUserLeftLobby = 6620;
	const ClientMMSInviteToLobby = 6621;
	const ClientMMSFlushFrenemyListCache = 6622;
	const ClientMMSFlushFrenemyListCacheResponse = 6623;
	const ClientMMSSetLobbyLinked = 6624;
	const NonStdMsgBase = 6800;
	const NonStdMsgMemcached = 6801;
	const NonStdMsgHTTPServer = 6802;
	const NonStdMsgHTTPClient = 6803;
	const NonStdMsgWGResponse = 6804;
	const NonStdMsgPHPSimulator = 6805;
	const NonStdMsgChase = 6806;
	const NonStdMsgDFSTransfer = 6807;
	const NonStdMsgTests = 6808;
	const NonStdMsgUMQpipeAAPL = 6809;
	const NonStdMsgSyslog = 6810; // obsolete
	const NonStdMsgLogsink = 6811;
	const NonStdMsgSteam2Emulator = 6812;
	const NonStdMsgRTMPServer = 6813;
	const UDSBase = 7000;
	const ClientUDSP2PSessionStarted = 7001;
	const ClientUDSP2PSessionEnded = 7002;
	const UDSRenderUserAuth = 7003;
	const UDSRenderUserAuthResponse = 7004;
	const ClientUDSInviteToGame = 7005;
	const UDSFindSession = 7006; // obsolete "renamed to UDSHasSession"
	const UDSHasSession = 7006;
	const UDSFindSessionResponse = 7007; // obsolete "renamed to UDSHasSessionResponse"
	const UDSHasSessionResponse = 7007;
	const MPASBase = 7100;
	const MPASVacBanReset = 7101;
	const KGSBase = 7200;
	const KGSAllocateKeyRange = 7201; // obsolete
	const KGSAllocateKeyRangeResponse = 7202; // obsolete
	const KGSGenerateKeys = 7203; // obsolete
	const KGSGenerateKeysResponse = 7204; // obsolete
	const KGSRemapKeys = 7205; // obsolete
	const KGSRemapKeysResponse = 7206; // obsolete
	const KGSGenerateGameStopWCKeys = 7207; // obsolete
	const KGSGenerateGameStopWCKeysResponse = 7208; // obsolete
	const UCMBase = 7300;
	const ClientUCMAddScreenshot = 7301;
	const ClientUCMAddScreenshotResponse = 7302;
	const UCMValidateObjectExists = 7303; // obsolete
	const UCMValidateObjectExistsResponse = 7304; // obsolete
	const UCMResetCommunityContent = 7307;
	const UCMResetCommunityContentResponse = 7308;
	const ClientUCMDeleteScreenshot = 7309;
	const ClientUCMDeleteScreenshotResponse = 7310;
	const ClientUCMPublishFile = 7311;
	const ClientUCMPublishFileResponse = 7312;
	const ClientUCMGetPublishedFileDetails = 7313; // obsolete
	const ClientUCMGetPublishedFileDetailsResponse = 7314; // obsolete
	const ClientUCMDeletePublishedFile = 7315;
	const ClientUCMDeletePublishedFileResponse = 7316;
	const ClientUCMEnumerateUserPublishedFiles = 7317;
	const ClientUCMEnumerateUserPublishedFilesResponse = 7318;
	const ClientUCMSubscribePublishedFile = 7319; // obsolete
	const ClientUCMSubscribePublishedFileResponse = 7320; // obsolete
	const ClientUCMEnumerateUserSubscribedFiles = 7321;
	const ClientUCMEnumerateUserSubscribedFilesResponse = 7322;
	const ClientUCMUnsubscribePublishedFile = 7323; // obsolete
	const ClientUCMUnsubscribePublishedFileResponse = 7324; // obsolete
	const ClientUCMUpdatePublishedFile = 7325;
	const ClientUCMUpdatePublishedFileResponse = 7326;
	const UCMUpdatePublishedFile = 7327;
	const UCMUpdatePublishedFileResponse = 7328;
	const UCMDeletePublishedFile = 7329;
	const UCMDeletePublishedFileResponse = 7330;
	const UCMUpdatePublishedFileStat = 7331;
	const UCMUpdatePublishedFileBan = 7332;
	const UCMUpdatePublishedFileBanResponse = 7333;
	const UCMUpdateTaggedScreenshot = 7334; // obsolete
	const UCMAddTaggedScreenshot = 7335; // obsolete
	const UCMRemoveTaggedScreenshot = 7336; // obsolete
	const UCMReloadPublishedFile = 7337;
	const UCMReloadUserFileListCaches = 7338;
	const UCMPublishedFileReported = 7339;
	const UCMUpdatePublishedFileIncompatibleStatus = 7340;
	const UCMPublishedFilePreviewAdd = 7341;
	const UCMPublishedFilePreviewAddResponse = 7342;
	const UCMPublishedFilePreviewRemove = 7343;
	const UCMPublishedFilePreviewRemoveResponse = 7344;
	const UCMPublishedFilePreviewChangeSortOrder = 7345; // obsolete
	const UCMPublishedFilePreviewChangeSortOrderResponse = 7346; // obsolete
	const ClientUCMPublishedFileSubscribed = 7347;
	const ClientUCMPublishedFileUnsubscribed = 7348;
	const UCMPublishedFileSubscribed = 7349;
	const UCMPublishedFileUnsubscribed = 7350;
	const UCMPublishFile = 7351;
	const UCMPublishFileResponse = 7352;
	const UCMPublishedFileChildAdd = 7353;
	const UCMPublishedFileChildAddResponse = 7354;
	const UCMPublishedFileChildRemove = 7355;
	const UCMPublishedFileChildRemoveResponse = 7356;
	const UCMPublishedFileChildChangeSortOrder = 7357; // obsolete
	const UCMPublishedFileChildChangeSortOrderResponse = 7358; // obsolete
	const UCMPublishedFileParentChanged = 7359;
	const ClientUCMGetPublishedFilesForUser = 7360;
	const ClientUCMGetPublishedFilesForUserResponse = 7361;
	const UCMGetPublishedFilesForUser = 7362; // obsolete
	const UCMGetPublishedFilesForUserResponse = 7363; // obsolete
	const ClientUCMSetUserPublishedFileAction = 7364;
	const ClientUCMSetUserPublishedFileActionResponse = 7365;
	const ClientUCMEnumeratePublishedFilesByUserAction = 7366;
	const ClientUCMEnumeratePublishedFilesByUserActionResponse = 7367;
	const ClientUCMPublishedFileDeleted = 7368;
	const UCMGetUserSubscribedFiles = 7369;
	const UCMGetUserSubscribedFilesResponse = 7370;
	const UCMFixStatsPublishedFile = 7371;
	const UCMDeleteOldScreenshot = 7372; // obsolete
	const UCMDeleteOldScreenshotResponse = 7373; // obsolete
	const UCMDeleteOldVideo = 7374; // obsolete
	const UCMDeleteOldVideoResponse = 7375; // obsolete
	const UCMUpdateOldScreenshotPrivacy = 7376; // obsolete
	const UCMUpdateOldScreenshotPrivacyResponse = 7377; // obsolete
	const ClientUCMEnumerateUserSubscribedFilesWithUpdates = 7378;
	const ClientUCMEnumerateUserSubscribedFilesWithUpdatesResponse = 7379;
	const UCMPublishedFileContentUpdated = 7380;
	const UCMPublishedFileUpdated = 7381;
	const ClientWorkshopItemChangesRequest = 7382;
	const ClientWorkshopItemChangesResponse = 7383;
	const ClientWorkshopItemInfoRequest = 7384;
	const ClientWorkshopItemInfoResponse = 7385;
	const FSBase = 7500;
	const ClientRichPresenceUpload = 7501;
	const ClientRichPresenceRequest = 7502;
	const ClientRichPresenceInfo = 7503;
	const FSRichPresenceRequest = 7504;
	const FSRichPresenceResponse = 7505;
	const FSComputeFrenematrix = 7506;
	const FSComputeFrenematrixResponse = 7507;
	const FSPlayStatusNotification = 7508;
	const FSPublishPersonaStatus = 7509;
	const FSAddOrRemoveFollower = 7510;
	const FSAddOrRemoveFollowerResponse = 7511;
	const FSUpdateFollowingList = 7512;
	const FSCommentNotification = 7513;
	const FSCommentNotificationViewed = 7514;
	const ClientFSGetFollowerCount = 7515;
	const ClientFSGetFollowerCountResponse = 7516;
	const ClientFSGetIsFollowing = 7517;
	const ClientFSGetIsFollowingResponse = 7518;
	const ClientFSEnumerateFollowingList = 7519;
	const ClientFSEnumerateFollowingListResponse = 7520;
	const FSGetPendingNotificationCount = 7521;
	const FSGetPendingNotificationCountResponse = 7522;
	const ClientFSOfflineMessageNotification = 7523;
	const ClientFSRequestOfflineMessageCount = 7524;
	const ClientFSGetFriendMessageHistory = 7525;
	const ClientFSGetFriendMessageHistoryResponse = 7526;
	const ClientFSGetFriendMessageHistoryForOfflineMessages = 7527;
	const ClientFSGetFriendsSteamLevels = 7528;
	const ClientFSGetFriendsSteamLevelsResponse = 7529;
	const FSRequestFriendData = 7530;
	const DRMRange2 = 7600;
	const CEGVersionSetEnableDisableRequest = 7600;
	const CEGVersionSetEnableDisableResponse = 7601;
	const CEGPropStatusDRMSRequest = 7602;
	const CEGPropStatusDRMSResponse = 7603;
	const CEGWhackFailureReportRequest = 7604;
	const CEGWhackFailureReportResponse = 7605;
	const DRMSFetchVersionSet = 7606;
	const DRMSFetchVersionSetResponse = 7607;
	const EconBase = 7700;
	const EconTrading_InitiateTradeRequest = 7701;
	const EconTrading_InitiateTradeProposed = 7702;
	const EconTrading_InitiateTradeResponse = 7703;
	const EconTrading_InitiateTradeResult = 7704;
	const EconTrading_StartSession = 7705;
	const EconTrading_CancelTradeRequest = 7706;
	const EconFlushInventoryCache = 7707;
	const EconFlushInventoryCacheResponse = 7708;
	const EconCDKeyProcessTransaction = 7711;
	const EconCDKeyProcessTransactionResponse = 7712;
	const EconGetErrorLogs = 7713;
	const EconGetErrorLogsResponse = 7714;
	const RMRange = 7800;
	const RMTestVerisignOTP = 7800;
	const RMTestVerisignOTPResponse = 7801;
	const RMDeleteMemcachedKeys = 7803;
	const RMRemoteInvoke = 7804;
	const BadLoginIPList = 7805;
	const RMMsgTraceAddTrigger = 7806;
	const RMMsgTraceRemoveTrigger = 7807;
	const RMMsgTraceEvent = 7808;
	const UGSBase = 7900;
	const UGSUpdateGlobalStats = 7900;
	const ClientUGSGetGlobalStats = 7901;
	const ClientUGSGetGlobalStatsResponse = 7902;
	const StoreBase = 8000;
	const StoreUpdateRecommendationCount = 8000; // obsolete
	const UMQBase = 8100;
	const UMQLogonRequest = 8100;
	const UMQLogonResponse = 8101;
	const UMQLogoffRequest = 8102;
	const UMQLogoffResponse = 8103;
	const UMQSendChatMessage = 8104;
	const UMQIncomingChatMessage = 8105;
	const UMQPoll = 8106;
	const UMQPollResults = 8107;
	const UMQ2AM_ClientMsgBatch = 8108;
	const UMQEnqueueMobileSalePromotions = 8109; // obsolete
	const UMQEnqueueMobileAnnouncements = 8110; // obsolete
	const WorkshopBase = 8200;
	const WorkshopAcceptTOSRequest = 8200; // obsolete
	const WorkshopAcceptTOSResponse = 8201; // obsolete
	const WebAPIBase = 8300;
	const WebAPIValidateOAuth2Token = 8300;
	const WebAPIValidateOAuth2TokenResponse = 8301;
	const WebAPIInvalidateTokensForAccount = 8302; // obsolete
	const WebAPIRegisterGCInterfaces = 8303;
	const WebAPIInvalidateOAuthClientCache = 8304;
	const WebAPIInvalidateOAuthTokenCache = 8305;
	const WebAPISetSecrets = 8306;
	const BackpackBase = 8400;
	const BackpackAddToCurrency = 8401;
	const BackpackAddToCurrencyResponse = 8402;
	const CREBase = 8500;
	const CRERankByTrend = 8501; // obsolete
	const CRERankByTrendResponse = 8502; // obsolete
	const CREItemVoteSummary = 8503;
	const CREItemVoteSummaryResponse = 8504;
	const CRERankByVote = 8505; // obsolete
	const CRERankByVoteResponse = 8506; // obsolete
	const CREUpdateUserPublishedItemVote = 8507;
	const CREUpdateUserPublishedItemVoteResponse = 8508;
	const CREGetUserPublishedItemVoteDetails = 8509;
	const CREGetUserPublishedItemVoteDetailsResponse = 8510;
	const CREEnumeratePublishedFiles = 8511;
	const CREEnumeratePublishedFilesResponse = 8512;
	const CREPublishedFileVoteAdded = 8513;
	const SecretsBase = 8600;
	const SecretsRequestCredentialPair = 8600;
	const SecretsCredentialPairResponse = 8601;
	const SecretsRequestServerIdentity = 8602; // obsolete
	const SecretsServerIdentityResponse = 8603; // obsolete
	const SecretsUpdateServerIdentities = 8604; // obsolete
	const BoxMonitorBase = 8700;
	const BoxMonitorReportRequest = 8700;
	const BoxMonitorReportResponse = 8701;
	const LogsinkBase = 8800;
	const LogsinkWriteReport = 8800;
	const PICSBase = 8900;
	const ClientPICSChangesSinceRequest = 8901;
	const ClientPICSChangesSinceResponse = 8902;
	const ClientPICSProductInfoRequest = 8903;
	const ClientPICSProductInfoResponse = 8904;
	const ClientPICSAccessTokenRequest = 8905;
	const ClientPICSAccessTokenResponse = 8906;
	const WorkerProcess = 9000;
	const WorkerProcessPingRequest = 9000;
	const WorkerProcessPingResponse = 9001;
	const WorkerProcessShutdown = 9002;
	const DRMWorkerProcess = 9100;
	const DRMWorkerProcessDRMAndSign = 9100;
	const DRMWorkerProcessDRMAndSignResponse = 9101;
	const DRMWorkerProcessSteamworksInfoRequest = 9102;
	const DRMWorkerProcessSteamworksInfoResponse = 9103;
	const DRMWorkerProcessInstallDRMDLLRequest = 9104;
	const DRMWorkerProcessInstallDRMDLLResponse = 9105;
	const DRMWorkerProcessSecretIdStringRequest = 9106;
	const DRMWorkerProcessSecretIdStringResponse = 9107;
	const DRMWorkerProcessGetDRMGuidsFromFileRequest = 9108; // obsolete
	const DRMWorkerProcessGetDRMGuidsFromFileResponse = 9109; // obsolete
	const DRMWorkerProcessInstallProcessedFilesRequest = 9110;
	const DRMWorkerProcessInstallProcessedFilesResponse = 9111;
	const DRMWorkerProcessExamineBlobRequest = 9112;
	const DRMWorkerProcessExamineBlobResponse = 9113;
	const DRMWorkerProcessDescribeSecretRequest = 9114;
	const DRMWorkerProcessDescribeSecretResponse = 9115;
	const DRMWorkerProcessBackfillOriginalRequest = 9116;
	const DRMWorkerProcessBackfillOriginalResponse = 9117;
	const DRMWorkerProcessValidateDRMDLLRequest = 9118;
	const DRMWorkerProcessValidateDRMDLLResponse = 9119;
	const DRMWorkerProcessValidateFileRequest = 9120;
	const DRMWorkerProcessValidateFileResponse = 9121;
	const DRMWorkerProcessSplitAndInstallRequest = 9122;
	const DRMWorkerProcessSplitAndInstallResponse = 9123;
	const DRMWorkerProcessGetBlobRequest = 9124;
	const DRMWorkerProcessGetBlobResponse = 9125;
	const DRMWorkerProcessEvaluateCrashRequest = 9126;
	const DRMWorkerProcessEvaluateCrashResponse = 9127;
	const DRMWorkerProcessAnalyzeFileRequest = 9128;
	const DRMWorkerProcessAnalyzeFileResponse = 9129;
	const DRMWorkerProcessUnpackBlobRequest = 9130;
	const DRMWorkerProcessUnpackBlobResponse = 9131;
	const DRMWorkerProcessInstallAllRequest = 9132;
	const DRMWorkerProcessInstallAllResponse = 9133;
	const TestWorkerProcess = 9200;
	const TestWorkerProcessLoadUnloadModuleRequest = 9200;
	const TestWorkerProcessLoadUnloadModuleResponse = 9201;
	const TestWorkerProcessServiceModuleCallRequest = 9202;
	const TestWorkerProcessServiceModuleCallResponse = 9203;
	const QuestServerBase = 9300;
	const ClientGetEmoticonList = 9330;
	const ClientEmoticonList = 9331;
	const ClientSharedLibraryBase = 9400; // obsolete "renamed to SLCBase"
	const SLCBase = 9400;
	const SLCUserSessionStatus = 9400;
	const SLCRequestUserSessionStatus = 9401;
	const SLCSharedLicensesLockStatus = 9402;
	const ClientSharedLicensesLockStatus = 9403; // obsolete
	const ClientSharedLicensesStopPlaying = 9404; // obsolete
	const ClientSharedLibraryLockStatus = 9405;
	const ClientSharedLibraryStopPlaying = 9406;
	const SLCOwnerLibraryChanged = 9407;
	const SLCSharedLibraryChanged = 9408;
	const RemoteClientBase = 9500;
	const RemoteClientAuth = 9500;
	const RemoteClientAuthResponse = 9501;
	const RemoteClientAppStatus = 9502;
	const RemoteClientStartStream = 9503;
	const RemoteClientStartStreamResponse = 9504;
	const RemoteClientPing = 9505;
	const RemoteClientPingResponse = 9506;
	const ClientUnlockStreaming = 9507;
	const ClientUnlockStreamingResponse = 9508;
	const RemoteClientAcceptEULA = 9509;
	const RemoteClientGetControllerConfig = 9510;
	const RemoteClientGetControllerConfigResposne = 9511;
	const RemoteClientStreamingEnabled = 9512;
	const ClientConcurrentSessionsBase = 9600;
	const ClientPlayingSessionState = 9600;
	const ClientKickPlayingSession = 9601;
	const ClientBroadcastBase = 9700;
	const ClientBroadcastInit = 9700;
	const ClientBroadcastFrames = 9701;
	const ClientBroadcastDisconnect = 9702;
	const ClientBroadcastScreenshot = 9703;
	const ClientBroadcastUploadConfig = 9704;
	const BaseClient3 = 9800;
	const ClientVoiceCallPreAuthorize = 9800;
	const ClientVoiceCallPreAuthorizeResponse = 9801;

	public static function getAllEnums()
	{
		$class = new \ReflectionClass(get_called_class());
		return $class->getConstants();
	}

	public static function getByName($name)
	{
		$constants = self::getAllEnums();
		if (array_key_exists($name, $constants)) {
			return $constants[$name];
		}

		return false;
	}

	public static function getByValue($value)
	{
		$constants = self::getAllEnums();
		$key = array_search($value, $constants);
		if ($key !== null || $key !== false) {
			return $key;
		}

		return false;
	}
}
?>