<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : steamclient/steammessages_depotbuilder.steamclient.proto
 */


namespace SteamKit\Base\Unified\SteamMsgDepotBuilder;

/**
 * Protobuf message :
 * SteamKit.Base.Unified.SteamMsgDepotBuilder.CContentBuilder_InitDepotBuild_Response
 */
class CContentBuilder_InitDepotBuild_Response extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * baseline_manifestid optional uint64 = 1
     *
     * @var int
     */
    protected $baseline_manifestid = null;

    /**
     * chunk_size optional uint32 = 2
     *
     * @var int
     */
    protected $chunk_size = null;

    /**
     * aes_key optional bytes = 3
     *
     * @var \Protobuf\Stream
     */
    protected $aes_key = null;

    /**
     * rsa_key optional bytes = 4
     *
     * @var \Protobuf\Stream
     */
    protected $rsa_key = null;

    /**
     * url_host optional string = 5
     *
     * @var string
     */
    protected $url_host = null;

    /**
     * Check if 'baseline_manifestid' has a value
     *
     * @return bool
     */
    public function hasBaselineManifestid()
    {
        return $this->baseline_manifestid !== null;
    }

    /**
     * Get 'baseline_manifestid' value
     *
     * @return int
     */
    public function getBaselineManifestid()
    {
        return $this->baseline_manifestid;
    }

    /**
     * Set 'baseline_manifestid' value
     *
     * @param int $value
     */
    public function setBaselineManifestid($value = null)
    {
        $this->baseline_manifestid = $value;
    }

    /**
     * Check if 'chunk_size' has a value
     *
     * @return bool
     */
    public function hasChunkSize()
    {
        return $this->chunk_size !== null;
    }

    /**
     * Get 'chunk_size' value
     *
     * @return int
     */
    public function getChunkSize()
    {
        return $this->chunk_size;
    }

    /**
     * Set 'chunk_size' value
     *
     * @param int $value
     */
    public function setChunkSize($value = null)
    {
        $this->chunk_size = $value;
    }

    /**
     * Check if 'aes_key' has a value
     *
     * @return bool
     */
    public function hasAesKey()
    {
        return $this->aes_key !== null;
    }

    /**
     * Get 'aes_key' value
     *
     * @return \Protobuf\Stream
     */
    public function getAesKey()
    {
        return $this->aes_key;
    }

    /**
     * Set 'aes_key' value
     *
     * @param \Protobuf\Stream $value
     */
    public function setAesKey($value = null)
    {
        if ($value !== null && ! $value instanceof \Protobuf\Stream) {
            $value = \Protobuf\Stream::wrap($value);
        }

        $this->aes_key = $value;
    }

    /**
     * Check if 'rsa_key' has a value
     *
     * @return bool
     */
    public function hasRsaKey()
    {
        return $this->rsa_key !== null;
    }

    /**
     * Get 'rsa_key' value
     *
     * @return \Protobuf\Stream
     */
    public function getRsaKey()
    {
        return $this->rsa_key;
    }

    /**
     * Set 'rsa_key' value
     *
     * @param \Protobuf\Stream $value
     */
    public function setRsaKey($value = null)
    {
        if ($value !== null && ! $value instanceof \Protobuf\Stream) {
            $value = \Protobuf\Stream::wrap($value);
        }

        $this->rsa_key = $value;
    }

    /**
     * Check if 'url_host' has a value
     *
     * @return bool
     */
    public function hasUrlHost()
    {
        return $this->url_host !== null;
    }

    /**
     * Get 'url_host' value
     *
     * @return string
     */
    public function getUrlHost()
    {
        return $this->url_host;
    }

    /**
     * Set 'url_host' value
     *
     * @param string $value
     */
    public function setUrlHost($value = null)
    {
        $this->url_host = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        $message = new self();
        $values  = array_merge([
            'baseline_manifestid' => null,
            'chunk_size' => null,
            'aes_key' => null,
            'rsa_key' => null,
            'url_host' => null
        ], $values);

        $message->setBaselineManifestid($values['baseline_manifestid']);
        $message->setChunkSize($values['chunk_size']);
        $message->setAesKey($values['aes_key']);
        $message->setRsaKey($values['rsa_key']);
        $message->setUrlHost($values['url_host']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'CContentBuilder_InitDepotBuild_Response',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'baseline_manifestid',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT64(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'chunk_size',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'aes_key',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BYTES(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 4,
                    'name' => 'rsa_key',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_BYTES(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 5,
                    'name' => 'url_host',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_STRING(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->baseline_manifestid !== null) {
            $writer->writeVarint($stream, 8);
            $writer->writeVarint($stream, $this->baseline_manifestid);
        }

        if ($this->chunk_size !== null) {
            $writer->writeVarint($stream, 16);
            $writer->writeVarint($stream, $this->chunk_size);
        }

        if ($this->aes_key !== null) {
            $writer->writeVarint($stream, 26);
            $writer->writeByteStream($stream, $this->aes_key);
        }

        if ($this->rsa_key !== null) {
            $writer->writeVarint($stream, 34);
            $writer->writeByteStream($stream, $this->rsa_key);
        }

        if ($this->url_host !== null) {
            $writer->writeVarint($stream, 42);
            $writer->writeString($stream, $this->url_host);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 4);

                $this->baseline_manifestid = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->chunk_size = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 12);

                $this->aes_key = $reader->readByteStream($stream);

                continue;
            }

            if ($tag === 4) {
                \Protobuf\WireFormat::assertWireType($wire, 12);

                $this->rsa_key = $reader->readByteStream($stream);

                continue;
            }

            if ($tag === 5) {
                \Protobuf\WireFormat::assertWireType($wire, 9);

                $this->url_host = $reader->readString($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->baseline_manifestid !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->baseline_manifestid);
        }

        if ($this->chunk_size !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->chunk_size);
        }

        if ($this->aes_key !== null) {
            $size += 1;
            $size += $calculator->computeByteStreamSize($this->aes_key);
        }

        if ($this->rsa_key !== null) {
            $size += 1;
            $size += $calculator->computeByteStreamSize($this->rsa_key);
        }

        if ($this->url_host !== null) {
            $size += 1;
            $size += $calculator->computeStringSize($this->url_host);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->baseline_manifestid = null;
        $this->chunk_size = null;
        $this->aes_key = null;
        $this->rsa_key = null;
        $this->url_host = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \SteamKit\Base\Unified\SteamMsgDepotBuilder\CContentBuilder_InitDepotBuild_Response) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->baseline_manifestid = ($message->baseline_manifestid !== null) ? $message->baseline_manifestid : $this->baseline_manifestid;
        $this->chunk_size = ($message->chunk_size !== null) ? $message->chunk_size : $this->chunk_size;
        $this->aes_key = ($message->aes_key !== null) ? $message->aes_key : $this->aes_key;
        $this->rsa_key = ($message->rsa_key !== null) ? $message->rsa_key : $this->rsa_key;
        $this->url_host = ($message->url_host !== null) ? $message->url_host : $this->url_host;
    }


}

