<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : steamclient/steammessages_inventory.steamclient.proto
 */


namespace SteamKit\Base\Unified\SteamMsgInventory;

/**
 * Protobuf service : SteamKit.Base.Unified.SteamMsgInventory.Inventory
 */
interface Inventory
{

    /**
     * @param \SteamKit\Base\Unified\SteamMsgInventory\CInventory_GetInventory_Request
     * $input
     * @return \SteamKit\Base\Unified\SteamMsgInventory\CInventory_Response
     */
    public function getInventory(\SteamKit\Base\Unified\SteamMsgInventory\CInventory_GetInventory_Request $input);
    /**
     * @param \SteamKit\Base\Unified\SteamMsgInventory\CInventory_ExchangeItem_Request
     * $input
     * @return \SteamKit\Base\Unified\SteamMsgInventory\CInventory_Response
     */
    public function exchangeItem(\SteamKit\Base\Unified\SteamMsgInventory\CInventory_ExchangeItem_Request $input);
    /**
     * @param \SteamKit\Base\Unified\SteamMsgInventory\CInventory_AddItem_Request
     * $input
     * @return \SteamKit\Base\Unified\SteamMsgInventory\CInventory_Response
     */
    public function addPromoItem(\SteamKit\Base\Unified\SteamMsgInventory\CInventory_AddItem_Request $input);
    /**
     * @param
     * \SteamKit\Base\Unified\SteamMsgInventory\CInventory_SafeModifyItem_Request
     * $input
     * @return \SteamKit\Base\Unified\SteamMsgInventory\CInventory_Response
     */
    public function safeModifyItem(\SteamKit\Base\Unified\SteamMsgInventory\CInventory_SafeModifyItem_Request $input);
    /**
     * @param
     * \SteamKit\Base\Unified\SteamMsgInventory\CInventory_ConsumePlaytime_Request
     * $input
     * @return \SteamKit\Base\Unified\SteamMsgInventory\CInventory_Response
     */
    public function consumePlaytime(\SteamKit\Base\Unified\SteamMsgInventory\CInventory_ConsumePlaytime_Request $input);
    /**
     * @param \SteamKit\Base\Unified\SteamMsgInventory\CInventory_GetItemDefs_Request
     * $input
     * @return \SteamKit\Base\Unified\SteamMsgInventory\CInventory_Response
     */
    public function getItemDefs(\SteamKit\Base\Unified\SteamMsgInventory\CInventory_GetItemDefs_Request $input);
    /**
     * @param \SteamKit\Base\Unified\SteamMsgInventory\CInventory_ConsumeItem_Request
     * $input
     * @return \SteamKit\Base\Unified\SteamMsgInventory\CInventory_Response
     */
    public function consumeItem(\SteamKit\Base\Unified\SteamMsgInventory\CInventory_ConsumeItem_Request $input);
    /**
     * @param \SteamKit\Base\Unified\SteamMsgInventory\CInventory_AddItem_Request
     * $input
     * @return \SteamKit\Base\Unified\SteamMsgInventory\CInventory_Response
     */
    public function devGenerateItem(\SteamKit\Base\Unified\SteamMsgInventory\CInventory_AddItem_Request $input);
    /**
     * @param
     * \SteamKit\Base\Unified\SteamMsgInventory\CInventory_DevSetNextDrop_Request
     * $input
     * @return \SteamKit\Base\Unified\SteamMsgInventory\CInventory_Response
     */
    public function devSetNextDrop(\SteamKit\Base\Unified\SteamMsgInventory\CInventory_DevSetNextDrop_Request $input);
    /**
     * @param
     * \SteamKit\Base\Unified\SteamMsgInventory\CInventory_SplitItemStack_Request
     * $input
     * @return \SteamKit\Base\Unified\SteamMsgInventory\CInventory_Response
     */
    public function splitItemStack(\SteamKit\Base\Unified\SteamMsgInventory\CInventory_SplitItemStack_Request $input);
    /**
     * @param
     * \SteamKit\Base\Unified\SteamMsgInventory\CInventory_CombineItemStacks_Request
     * $input
     * @return \SteamKit\Base\Unified\SteamMsgInventory\CInventory_Response
     */
    public function combineItemStacks(\SteamKit\Base\Unified\SteamMsgInventory\CInventory_CombineItemStacks_Request $input);
    /**
     * @param
     * \SteamKit\Base\Unified\SteamMsgInventory\CInventory_GetItemDefMeta_Request
     * $input
     * @return
     * \SteamKit\Base\Unified\SteamMsgInventory\CInventory_GetItemDefMeta_Response
     */
    public function getItemDefMeta(\SteamKit\Base\Unified\SteamMsgInventory\CInventory_GetItemDefMeta_Request $input);

}

