<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : csgo/base_gcmessages.proto
 */


namespace SteamKit\Base\GC\CSGO\SteamMsgGC;

/**
 * Protobuf message :
 * SteamKit.Base.GC.CSGO.SteamMsgGC.CGCStorePurchaseInit_LineItem
 */
class CGCStorePurchaseInit_LineItem extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * item_def_id optional uint32 = 1
     *
     * @var int
     */
    protected $item_def_id = null;

    /**
     * quantity optional uint32 = 2
     *
     * @var int
     */
    protected $quantity = null;

    /**
     * cost_in_local_currency optional uint32 = 3
     *
     * @var int
     */
    protected $cost_in_local_currency = null;

    /**
     * purchase_type optional uint32 = 4
     *
     * @var int
     */
    protected $purchase_type = null;

    /**
     * Check if 'item_def_id' has a value
     *
     * @return bool
     */
    public function hasItemDefId()
    {
        return $this->item_def_id !== null;
    }

    /**
     * Get 'item_def_id' value
     *
     * @return int
     */
    public function getItemDefId()
    {
        return $this->item_def_id;
    }

    /**
     * Set 'item_def_id' value
     *
     * @param int $value
     */
    public function setItemDefId($value = null)
    {
        $this->item_def_id = $value;
    }

    /**
     * Check if 'quantity' has a value
     *
     * @return bool
     */
    public function hasQuantity()
    {
        return $this->quantity !== null;
    }

    /**
     * Get 'quantity' value
     *
     * @return int
     */
    public function getQuantity()
    {
        return $this->quantity;
    }

    /**
     * Set 'quantity' value
     *
     * @param int $value
     */
    public function setQuantity($value = null)
    {
        $this->quantity = $value;
    }

    /**
     * Check if 'cost_in_local_currency' has a value
     *
     * @return bool
     */
    public function hasCostInLocalCurrency()
    {
        return $this->cost_in_local_currency !== null;
    }

    /**
     * Get 'cost_in_local_currency' value
     *
     * @return int
     */
    public function getCostInLocalCurrency()
    {
        return $this->cost_in_local_currency;
    }

    /**
     * Set 'cost_in_local_currency' value
     *
     * @param int $value
     */
    public function setCostInLocalCurrency($value = null)
    {
        $this->cost_in_local_currency = $value;
    }

    /**
     * Check if 'purchase_type' has a value
     *
     * @return bool
     */
    public function hasPurchaseType()
    {
        return $this->purchase_type !== null;
    }

    /**
     * Get 'purchase_type' value
     *
     * @return int
     */
    public function getPurchaseType()
    {
        return $this->purchase_type;
    }

    /**
     * Set 'purchase_type' value
     *
     * @param int $value
     */
    public function setPurchaseType($value = null)
    {
        $this->purchase_type = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        $message = new self();
        $values  = array_merge([
            'item_def_id' => null,
            'quantity' => null,
            'cost_in_local_currency' => null,
            'purchase_type' => null
        ], $values);

        $message->setItemDefId($values['item_def_id']);
        $message->setQuantity($values['quantity']);
        $message->setCostInLocalCurrency($values['cost_in_local_currency']);
        $message->setPurchaseType($values['purchase_type']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'CGCStorePurchaseInit_LineItem',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'item_def_id',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'quantity',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'cost_in_local_currency',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 4,
                    'name' => 'purchase_type',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->item_def_id !== null) {
            $writer->writeVarint($stream, 8);
            $writer->writeVarint($stream, $this->item_def_id);
        }

        if ($this->quantity !== null) {
            $writer->writeVarint($stream, 16);
            $writer->writeVarint($stream, $this->quantity);
        }

        if ($this->cost_in_local_currency !== null) {
            $writer->writeVarint($stream, 24);
            $writer->writeVarint($stream, $this->cost_in_local_currency);
        }

        if ($this->purchase_type !== null) {
            $writer->writeVarint($stream, 32);
            $writer->writeVarint($stream, $this->purchase_type);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->item_def_id = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->quantity = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->cost_in_local_currency = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 4) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->purchase_type = $reader->readVarint($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->item_def_id !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->item_def_id);
        }

        if ($this->quantity !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->quantity);
        }

        if ($this->cost_in_local_currency !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->cost_in_local_currency);
        }

        if ($this->purchase_type !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->purchase_type);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->item_def_id = null;
        $this->quantity = null;
        $this->cost_in_local_currency = null;
        $this->purchase_type = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \SteamKit\Base\GC\CSGO\SteamMsgGC\CGCStorePurchaseInit_LineItem) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->item_def_id = ($message->item_def_id !== null) ? $message->item_def_id : $this->item_def_id;
        $this->quantity = ($message->quantity !== null) ? $message->quantity : $this->quantity;
        $this->cost_in_local_currency = ($message->cost_in_local_currency !== null) ? $message->cost_in_local_currency : $this->cost_in_local_currency;
        $this->purchase_type = ($message->purchase_type !== null) ? $message->purchase_type : $this->purchase_type;
    }


}

