<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : csgo/base_gcmessages.proto
 */


namespace SteamKit\Base\GC\CSGO\SteamMsgGC;

/**
 * Protobuf message : SteamKit.Base.GC.CSGO.SteamMsgGC.CMsgApplyStrangePart
 */
class CMsgApplyStrangePart extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * strange_part_item_id optional uint64 = 1
     *
     * @var int
     */
    protected $strange_part_item_id = null;

    /**
     * item_item_id optional uint64 = 2
     *
     * @var int
     */
    protected $item_item_id = null;

    /**
     * Check if 'strange_part_item_id' has a value
     *
     * @return bool
     */
    public function hasStrangePartItemId()
    {
        return $this->strange_part_item_id !== null;
    }

    /**
     * Get 'strange_part_item_id' value
     *
     * @return int
     */
    public function getStrangePartItemId()
    {
        return $this->strange_part_item_id;
    }

    /**
     * Set 'strange_part_item_id' value
     *
     * @param int $value
     */
    public function setStrangePartItemId($value = null)
    {
        $this->strange_part_item_id = $value;
    }

    /**
     * Check if 'item_item_id' has a value
     *
     * @return bool
     */
    public function hasItemItemId()
    {
        return $this->item_item_id !== null;
    }

    /**
     * Get 'item_item_id' value
     *
     * @return int
     */
    public function getItemItemId()
    {
        return $this->item_item_id;
    }

    /**
     * Set 'item_item_id' value
     *
     * @param int $value
     */
    public function setItemItemId($value = null)
    {
        $this->item_item_id = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        $message = new self();
        $values  = array_merge([
            'strange_part_item_id' => null,
            'item_item_id' => null
        ], $values);

        $message->setStrangePartItemId($values['strange_part_item_id']);
        $message->setItemItemId($values['item_item_id']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'CMsgApplyStrangePart',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'strange_part_item_id',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT64(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'item_item_id',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT64(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->strange_part_item_id !== null) {
            $writer->writeVarint($stream, 8);
            $writer->writeVarint($stream, $this->strange_part_item_id);
        }

        if ($this->item_item_id !== null) {
            $writer->writeVarint($stream, 16);
            $writer->writeVarint($stream, $this->item_item_id);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 4);

                $this->strange_part_item_id = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 4);

                $this->item_item_id = $reader->readVarint($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->strange_part_item_id !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->strange_part_item_id);
        }

        if ($this->item_item_id !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->item_item_id);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->strange_part_item_id = null;
        $this->item_item_id = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \SteamKit\Base\GC\CSGO\SteamMsgGC\CMsgApplyStrangePart) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->strange_part_item_id = ($message->strange_part_item_id !== null) ? $message->strange_part_item_id : $this->strange_part_item_id;
        $this->item_item_id = ($message->item_item_id !== null) ? $message->item_item_id : $this->item_item_id;
    }


}

