<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : csgo/base_gcmessages.proto
 */


namespace SteamKit\Base\GC\CSGO\SteamMsgGC;

/**
 * Protobuf message :
 * SteamKit.Base.GC.CSGO.SteamMsgGC.CMsgGCIncrementKillCountResponse
 */
class CMsgGCIncrementKillCountResponse extends \Protobuf\AbstractMessage
{

    /**
     * @var \Protobuf\UnknownFieldSet
     */
    protected $unknownFieldSet = null;

    /**
     * @var \Protobuf\Extension\ExtensionFieldMap
     */
    protected $extensions = null;

    /**
     * killer_account_id optional uint32 = 1
     *
     * @var int
     */
    protected $killer_account_id = null;

    /**
     * num_kills optional uint32 = 2
     *
     * @var int
     */
    protected $num_kills = null;

    /**
     * item_def optional uint32 = 3
     *
     * @var int
     */
    protected $item_def = null;

    /**
     * level_type optional uint32 = 4
     *
     * @var int
     */
    protected $level_type = null;

    /**
     * Check if 'killer_account_id' has a value
     *
     * @return bool
     */
    public function hasKillerAccountId()
    {
        return $this->killer_account_id !== null;
    }

    /**
     * Get 'killer_account_id' value
     *
     * @return int
     */
    public function getKillerAccountId()
    {
        return $this->killer_account_id;
    }

    /**
     * Set 'killer_account_id' value
     *
     * @param int $value
     */
    public function setKillerAccountId($value = null)
    {
        $this->killer_account_id = $value;
    }

    /**
     * Check if 'num_kills' has a value
     *
     * @return bool
     */
    public function hasNumKills()
    {
        return $this->num_kills !== null;
    }

    /**
     * Get 'num_kills' value
     *
     * @return int
     */
    public function getNumKills()
    {
        return $this->num_kills;
    }

    /**
     * Set 'num_kills' value
     *
     * @param int $value
     */
    public function setNumKills($value = null)
    {
        $this->num_kills = $value;
    }

    /**
     * Check if 'item_def' has a value
     *
     * @return bool
     */
    public function hasItemDef()
    {
        return $this->item_def !== null;
    }

    /**
     * Get 'item_def' value
     *
     * @return int
     */
    public function getItemDef()
    {
        return $this->item_def;
    }

    /**
     * Set 'item_def' value
     *
     * @param int $value
     */
    public function setItemDef($value = null)
    {
        $this->item_def = $value;
    }

    /**
     * Check if 'level_type' has a value
     *
     * @return bool
     */
    public function hasLevelType()
    {
        return $this->level_type !== null;
    }

    /**
     * Get 'level_type' value
     *
     * @return int
     */
    public function getLevelType()
    {
        return $this->level_type;
    }

    /**
     * Set 'level_type' value
     *
     * @param int $value
     */
    public function setLevelType($value = null)
    {
        $this->level_type = $value;
    }

    /**
     * {@inheritdoc}
     */
    public function extensions()
    {
        if ( $this->extensions !== null) {
            return $this->extensions;
        }

        return $this->extensions = new \Protobuf\Extension\ExtensionFieldMap(__CLASS__);
    }

    /**
     * {@inheritdoc}
     */
    public function unknownFieldSet()
    {
        return $this->unknownFieldSet;
    }

    /**
     * {@inheritdoc}
     */
    public static function fromStream($stream, \Protobuf\Configuration $configuration = null)
    {
        return new self($stream, $configuration);
    }

    /**
     * {@inheritdoc}
     */
    public static function fromArray(array $values)
    {
        $message = new self();
        $values  = array_merge([
            'killer_account_id' => null,
            'num_kills' => null,
            'item_def' => null,
            'level_type' => null
        ], $values);

        $message->setKillerAccountId($values['killer_account_id']);
        $message->setNumKills($values['num_kills']);
        $message->setItemDef($values['item_def']);
        $message->setLevelType($values['level_type']);

        return $message;
    }

    /**
     * {@inheritdoc}
     */
    public static function descriptor()
    {
        return \google\protobuf\DescriptorProto::fromArray([
            'name'      => 'CMsgGCIncrementKillCountResponse',
            'field'     => [
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 1,
                    'name' => 'killer_account_id',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 2,
                    'name' => 'num_kills',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 3,
                    'name' => 'item_def',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
                \google\protobuf\FieldDescriptorProto::fromArray([
                    'number' => 4,
                    'name' => 'level_type',
                    'type' => \google\protobuf\FieldDescriptorProto\Type::TYPE_UINT32(),
                    'label' => \google\protobuf\FieldDescriptorProto\Label::LABEL_OPTIONAL()
                ]),
            ],
        ]);
    }

    /**
     * {@inheritdoc}
     */
    public function toStream(\Protobuf\Configuration $configuration = null)
    {
        $config  = $configuration ?: \Protobuf\Configuration::getInstance();
        $context = $config->createWriteContext();
        $stream  = $context->getStream();

        $this->writeTo($context);
        $stream->seek(0);

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function writeTo(\Protobuf\WriteContext $context)
    {
        $stream      = $context->getStream();
        $writer      = $context->getWriter();
        $sizeContext = $context->getComputeSizeContext();

        if ($this->killer_account_id !== null) {
            $writer->writeVarint($stream, 8);
            $writer->writeVarint($stream, $this->killer_account_id);
        }

        if ($this->num_kills !== null) {
            $writer->writeVarint($stream, 16);
            $writer->writeVarint($stream, $this->num_kills);
        }

        if ($this->item_def !== null) {
            $writer->writeVarint($stream, 24);
            $writer->writeVarint($stream, $this->item_def);
        }

        if ($this->level_type !== null) {
            $writer->writeVarint($stream, 32);
            $writer->writeVarint($stream, $this->level_type);
        }

        if ($this->extensions !== null) {
            $this->extensions->writeTo($context);
        }

        return $stream;
    }

    /**
     * {@inheritdoc}
     */
    public function readFrom(\Protobuf\ReadContext $context)
    {
        $reader = $context->getReader();
        $length = $context->getLength();
        $stream = $context->getStream();

        $limit = ($length !== null)
            ? ($stream->tell() + $length)
            : null;

        while ($limit === null || $stream->tell() < $limit) {

            if ($stream->eof()) {
                break;
            }

            $key  = $reader->readVarint($stream);
            $wire = \Protobuf\WireFormat::getTagWireType($key);
            $tag  = \Protobuf\WireFormat::getTagFieldNumber($key);

            if ($stream->eof()) {
                break;
            }

            if ($tag === 1) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->killer_account_id = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 2) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->num_kills = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 3) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->item_def = $reader->readVarint($stream);

                continue;
            }

            if ($tag === 4) {
                \Protobuf\WireFormat::assertWireType($wire, 13);

                $this->level_type = $reader->readVarint($stream);

                continue;
            }

            $extensions = $context->getExtensionRegistry();
            $extension  = $extensions ? $extensions->findByNumber(__CLASS__, $tag) : null;

            if ($extension !== null) {
                $this->extensions()->add($extension, $extension->readFrom($context, $wire));

                continue;
            }

            if ($this->unknownFieldSet === null) {
                $this->unknownFieldSet = new \Protobuf\UnknownFieldSet();
            }

            $data    = $reader->readUnknown($stream, $wire);
            $unknown = new \Protobuf\Unknown($tag, $wire, $data);

            $this->unknownFieldSet->add($unknown);

        }
    }

    /**
     * {@inheritdoc}
     */
    public function serializedSize(\Protobuf\ComputeSizeContext $context)
    {
        $calculator = $context->getSizeCalculator();
        $size       = 0;

        if ($this->killer_account_id !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->killer_account_id);
        }

        if ($this->num_kills !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->num_kills);
        }

        if ($this->item_def !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->item_def);
        }

        if ($this->level_type !== null) {
            $size += 1;
            $size += $calculator->computeVarintSize($this->level_type);
        }

        if ($this->extensions !== null) {
            $size += $this->extensions->serializedSize($context);
        }

        return $size;
    }

    /**
     * {@inheritdoc}
     */
    public function clear()
    {
        $this->killer_account_id = null;
        $this->num_kills = null;
        $this->item_def = null;
        $this->level_type = null;
    }

    /**
     * {@inheritdoc}
     */
    public function merge(\Protobuf\Message $message)
    {
        if ( ! $message instanceof \SteamKit\Base\GC\CSGO\SteamMsgGC\CMsgGCIncrementKillCountResponse) {
            throw new \InvalidArgumentException(sprintf('Argument 1 passed to %s must be a %s, %s given', __METHOD__, __CLASS__, get_class($message)));
        }

        $this->killer_account_id = ($message->killer_account_id !== null) ? $message->killer_account_id : $this->killer_account_id;
        $this->num_kills = ($message->num_kills !== null) ? $message->num_kills : $this->num_kills;
        $this->item_def = ($message->item_def !== null) ? $message->item_def : $this->item_def;
        $this->level_type = ($message->level_type !== null) ? $message->level_type : $this->level_type;
    }


}

