<?php
/**
 * Generated by Protobuf protoc plugin.
 *
 * File descriptor : steamclient/steammessages_site_license.steamclient.proto
 */


namespace SteamKit\Base\Unified\SteamMsgSiteLicense;

/**
 * Protobuf service : SteamKit.Base.Unified.SteamMsgSiteLicense.SiteLicense
 */
interface SiteLicense
{

    /**
     * @param
     * \SteamKit\Base\Unified\SteamMsgSiteLicense\CSiteLicense_ClientSiteAssociation_Notification
     * $input
     * @return \SteamKit\Base\Unified\SteamMsgUnifiedBase\NoResponse
     */
    public function clientSiteAssociation(\SteamKit\Base\Unified\SteamMsgSiteLicense\CSiteLicense_ClientSiteAssociation_Notification $input);

}

